const SERIES=[
{name:'Karting',abbr:'KART',rounds:8,promotionRep:30,promotionPos:8,cost:1,salary:2,tracks:['Melbourne Kart Circuit','Sydney Kart Raceway','Gold Coast Karting','Adelaide Kart Park','Newcastle Kart Circuit','Phillip Island Kart Track','Perth Kart Arena','National Kart Final'],teams:[['Combes Racing Academy',49,72],['Velocity Juniors',55,76],['Apex Karting',61,81]]},
{name:'Formula 4',abbr:'F4',rounds:10,promotionRep:47,promotionPos:7,cost:3,salary:6,tracks:['Phillip Island','Sandown','The Bend','Sydney Motorsport Park','Queensland Raceway','Bathurst Support','Adelaide Street Circuit','Hidden Valley','Taupo','Albert Park'],teams:[['Southern Cross F4',57,73],['Velocity Motorsport',64,78],['Apex Junior Racing',71,83]]},
{name:'Formula 3',abbr:'F3',rounds:10,promotionRep:64,promotionPos:6,cost:6,salary:13,tracks:['Bahrain','Melbourne','Imola','Monaco','Barcelona','Spielberg','Silverstone','Spa','Monza','Yas Marina'],teams:[['Nova F3',64,75],['Apex GP',72,81],['Titan Motorsport',80,86]]},
{name:'Formula 2',abbr:'F2',rounds:12,promotionRep:80,promotionPos:5,cost:10,salary:25,tracks:['Bahrain','Jeddah','Melbourne','Imola','Monaco','Barcelona','Spielberg','Silverstone','Spa','Monza','Baku','Yas Marina'],teams:[['Nova F2',70,76],['Velocity GP',79,82],['Titan Formula',88,88]]},
{name:'Formula 1',abbr:'F1',rounds:16,promotionRep:999,promotionPos:1,cost:16,salary:70,tracks:['Melbourne','Suzuka','Monaco','Barcelona','Spielberg','Silverstone','Spa','Monza','Singapore','Austin','Mexico City','Interlagos','Las Vegas','Qatar','Bahrain','Abu Dhabi'],teams:[['Phoenix F1',78,79],['Velocity Racing',87,86],['Titan Grand Prix',96,92]]}
];
const FIRST=['Luca','Theo','Mika','Oscar','Hugo','Noah','Felix','Marco','Liam','Jack','Nico','Emil','Leo','Carlos','Pierre','Mateo','Yuki','Daniel','Rafael','Arthur','Oliver','Gabriel','Seb','Maxim','Alexei','James','Callum','Ethan'];
const LAST=['Moretti','Bennett','Keller','Rossi','Dubois','Tanaka','Santos','Muller','Ricci','Lawson','Hart','Vega','Martin','Nakamura','Costa','Bianchi','Novak','Turner','Fischer','Silva','Evans','Reid','Petrov','King','Duran','Mercer','Cole'];
const POINTS=[25,18,15,12,10,8,6,4,2,1];
const TRAINING={pace:['🏎️ Pace','Raw speed and qualifying'],racecraft:['⚔️ Racecraft','Starts, overtaking and defence'],consistency:['🎯 Consistency','Fewer spins and errors'],fitness:['💪 Fitness','Energy and late-race pace'],wet:['🌧️ Wet skill','Performance in rain'],feedback:['🧠 Feedback','Improves car development'],rest:['🛌 Rest','Restore energy']};
const ACHIEVEMENTS=[['firstWin','First Victory','Win your first race'],['firstPole','Pole Position','Take your first pole'],['champion','Champion','Win any championship'],['f1','Formula 1','Reach Formula 1'],['f1win','F1 Winner','Win a Formula 1 race'],['f1champ','World Champion','Win the Formula 1 championship']];
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>Math.random()*(b-a)+a,ri=(a,b)=>Math.floor(rnd(a,b+1));
function fresh(name='Alex Combes',nationality='Australia',archetype='balanced'){
 const base={pace:52,racecraft:51,consistency:52,fitness:50,wet:48,feedback:50};
 if(archetype==='qualifier'){base.pace+=6;base.racecraft-=3} if(archetype==='racer'){base.racecraft+=6;base.pace-=2} if(archetype==='rain'){base.wet+=9;base.consistency-=2} if(archetype==='steady'){base.consistency+=7;base.pace-=2}
 return {version:2,name,nationality,archetype,series:0,season:1,round:0,teamTier:0,points:0,rep:15,money:25,energy:100,morale:70,stats:base,carDev:0,reliabilityDev:0,trainingLeft:2,qualified:false,grid:null,weather:'Dry',strategy:{start:'balanced',tyre:'balanced',risk:'medium'},gridData:[],field:[],standings:{},history:[],results:[],offers:[],sponsor:null,achievements:{},career:{starts:0,wins:0,podiums:0,poles:0,points:0,championships:0,dnfs:0,bestFinish:99},seasonWins:0,seasonPodiums:0,seasonPoles:0,lastSeasonPos:null};
}
let S=load();
function save(silent=false){localStorage.setItem('roadToF1V2',JSON.stringify(S));if(!silent)status('Career saved.')}
function load(){try{const x=JSON.parse(localStorage.getItem('roadToF1V2'));return x&&x.version===2?x:null}catch{return null}}
function current(){return SERIES[S.series]} function team(){return current().teams[S.teamTier]} function car(){return clamp(team()[1]+S.carDev,1,99)} function reliability(){return clamp(team()[2]+S.reliabilityDev,40,99)} function fmt(n){return '$'+Math.round(n)+'k'}
function overall(){const x=S.stats;return Math.round(x.pace*.25+x.racecraft*.22+x.consistency*.18+x.fitness*.12+x.wet*.11+x.feedback*.12)}
function status(t){$('weekendStatus').textContent=t}
function addHistory(text,kind='event'){S.history.unshift({text,kind,season:S.season,series:current().name});S.history=S.history.slice(0,120)}
function setAchievement(k){if(!S.achievements[k]){S.achievements[k]=true;const a=ACHIEVEMENTS.find(x=>x[0]===k);if(a)addHistory(`🏆 Achievement unlocked: ${a[1]}`,'achievement')}}
function generateField(){
 const count=19,base=47+S.series*8; const used=new Set([S.name]); S.field=[];
 for(let i=0;i<count;i++){let name;do{name=`${FIRST[ri(0,FIRST.length-1)]} ${LAST[ri(0,LAST.length-1)]}`}while(used.has(name));used.add(name);const tier=i<5?2:i<12?1:0;S.field.push({id:'ai'+i,name,skill:clamp(base+rnd(-6,11),42,96),car:clamp(current().teams[tier][1]+rnd(-3,3),40,99),consistency:clamp(base+rnd(-7,10),40,96),wet:clamp(base+rnd(-10,12),35,98),points:0,wins:0});}
 S.standings={player:0};S.field.forEach(d=>S.standings[d.id]=0);
}
function ensureSeason(){if(!S.field||S.field.length!==19)generateField();if(!S.standings)generateField()}
function pickWeather(){const r=Math.random();S.weather=r<.18?'Wet':r<.34?'Mixed':'Dry'}
function trackType(track){const street=['Monaco','Singapore','Baku','Las Vegas','Adelaide','Melbourne'];if(street.some(x=>track.includes(x)))return'Street';if(['Spa','Silverstone','Suzuka','Spielberg'].some(x=>track.includes(x)))return'High speed';return'Balanced'}
function render(){if(!S)return;$('driverNameTop').textContent=S.name;$('driverName').textContent=S.name;$('profileName').textContent=S.name;$('seriesLabel').textContent=current().name;$('seasonNum').textContent=S.season;$('roundNum').textContent=`${S.round+1}/${current().rounds}`;$('points').textContent=S.points;$('reputation').textContent=Math.round(S.rep);$('money').textContent=fmt(S.money);$('energy').textContent=Math.round(S.energy)+'%';$('trackName').textContent=current().tracks[S.round]||'Season complete';$('weather').textContent=S.weather==='Wet'?'🌧️ Wet':S.weather==='Mixed'?'🌦️ Mixed':'☀️ Dry';$('weekendMeta').textContent=`${trackType(current().tracks[S.round]||'')} circuit • ${current().name} • ${team()[0]}`;$('overallRating').textContent=overall();$('teamName').textContent=team()[0];$('carRating').textContent=Math.round(car());$('carBar').style.width=car()+'%';$('reliabilityRating').textContent=Math.round(reliability());$('reliabilityBar').style.width=reliability()+'%';$('moraleRating').textContent=Math.round(S.morale);$('moraleBar').style.width=S.morale+'%';$('carStars').textContent='★'.repeat(S.teamTier+2)+'☆'.repeat(3-S.teamTier);$('trainingSessions').textContent=`${S.trainingLeft} sessions left`;$('qualifyingBadge').textContent=S.qualified?`P${S.grid}`:'Not run';$('gridBadge').textContent=S.qualified?`Start P${S.grid}`:'No grid position';$('raceBtn').disabled=!S.qualified;$('qualifyBtn').disabled=S.qualified;renderStepper();renderTraining();renderStats();renderQualifying();renderStandings();renderCareer();renderTeam();renderHistory();renderTarget();save(true)}
function renderStepper(){const steps=[['Prepare',S.trainingLeft<2],['Qualify',S.qualified],['Race',false]];$('weekendStep').innerHTML=steps.map((x,i)=>`<span class="step ${x[1]?'done':(!S.qualified&&i===0)||(S.qualified&&i===2)?'current':''}">${x[1]?'✓ ':''}${x[0]}</span>`).join('')}
function renderTraining(){$('trainingGrid').innerHTML=Object.entries(TRAINING).map(([k,v])=>`<button class="training" data-train="${k}" ${S.qualified||S.trainingLeft<=0?'disabled':''}><b>${v[0]}</b><small>${v[1]}${k==='rest'?'':` • ${fmt(current().cost)}`}</small></button>`).join('');document.querySelectorAll('[data-train]').forEach(b=>b.onclick=()=>train(b.dataset.train))}
function renderStats(){const labels={pace:'Raw pace',racecraft:'Racecraft',consistency:'Consistency',fitness:'Fitness',wet:'Wet skill',feedback:'Technical feedback'};const html=Object.entries(S.stats).map(([k,v])=>`<div class="attr-row"><div class="attr-top"><span>${labels[k]}</span><strong>${Math.round(v)}</strong></div><div class="bar"><i style="width:${v}%"></i></div></div>`).join('');$('stats').innerHTML=html;$('careerStats').innerHTML=html}
function renderQualifying(){if(!S.gridData.length){$('qualifyingResults').className='results-table empty-state';$('qualifyingResults').textContent='Qualifying results will appear here.';return}$('qualifyingResults').className='results-table';$('qualifyingResults').innerHTML=tableRows(S.gridData.slice(0,10),true)}
function tableRows(rows,qual=false){return `<div class="standing-row head"><span>Pos</span><span>Driver</span><span>${qual?'Team':'Wins'}</span><span>${qual?'Gap':'Pts'}</span></div>`+rows.map((d,i)=>`<div class="standing-row ${d.player?'player':''}"><span>${i+1}</span><span>${d.name}</span><span>${qual?(d.player?team()[0]:d.team):d.wins||0}</span><b>${qual?(i===0?'POLE':'+'+d.gap.toFixed(3)):Math.round(d.points)}</b></div>`).join('')}
function standingsRows(){const a=[{id:'player',name:S.name,points:S.standings.player||0,wins:S.seasonWins,player:true},...S.field.map(d=>({id:d.id,name:d.name,points:S.standings[d.id]||0,wins:d.wins||0}))];return a.sort((a,b)=>b.points-a.points||b.wins-a.wins)}
function renderStandings(){const rows=standingsRows();$('standingsTable').innerHTML=tableRows(rows,false);const pos=rows.findIndex(x=>x.player)+1;$('seasonSummary').innerHTML=details([['Championship position',`P${pos}`],['Points',S.points],['Wins',S.seasonWins],['Podiums',S.seasonPodiums],['Poles',S.seasonPoles],['Rounds complete',`${S.round}/${current().rounds}`]]);$('recentResults').innerHTML=S.results.slice(0,6).map(r=>`<div class="recent"><b>${r.finish}</b> • ${r.track}<br><span class="muted">Started ${r.start} • ${r.points} pts</span></div>`).join('')||'<p class="muted">No results yet.</p>'}
function details(rows){return rows.map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
function renderCareer(){const rank=standingsRows().findIndex(x=>x.player)+1;$('ladder').innerHTML=SERIES.map((x,i)=>`<div class="ladder-step ${i===S.series?'active':''}"><span>${i<S.series?'✓':i===S.series?'🏁':'○'} ${x.name}</span><small>${i===S.series?'Current':i<S.series?'Completed':`Need rep ${x.promotionRep}`}</small></div>`).join('');$('profileDetails').innerHTML=details([['Nationality',S.nationality],['Series',current().name],['Team',team()[0]],['Driver rating',overall()],['Reputation',Math.round(S.rep)],['Current rank',`P${rank}`]]);$('careerTotals').innerHTML=details([['Starts',S.career.starts],['Wins',S.career.wins],['Podiums',S.career.podiums],['Poles',S.career.poles],['Career points',S.career.points],['Championships',S.career.championships],['DNFs',S.career.dnfs]]);$('achievements').innerHTML=ACHIEVEMENTS.map(a=>`<div class="achievement ${S.achievements[a[0]]?'unlocked':''}"><b>${S.achievements[a[0]]?'✓ ':'○ '}${a[1]}</b><span>${a[2]}</span></div>`).join('')}
function renderTarget(){const target=S.series===4?(S.teamTier===2?'Win the World Championship':'Beat your team target'):`Finish top ${current().promotionPos} & reach ${current().promotionRep} reputation`;$('seasonTarget').textContent=target;const pos=standingsRows().findIndex(x=>x.player)+1;$('targetProgress').textContent=`Currently P${pos} with ${Math.round(S.rep)} reputation.`}
function renderTeam(){$('contractTeam').textContent=team()[0];$('contractSalary').textContent=`${fmt(current().salary*(S.teamTier+1))}/race`;$('contractDetails').innerHTML=details([['Series',current().name],['Team level',S.teamTier===0?'Developing':S.teamTier===1?'Competitive':'Front-running'],['Car',Math.round(car())],['Reliability',Math.round(reliability())],['Morale',Math.round(S.morale)]]);$('offers').innerHTML=S.offers.length?S.offers.map((o,i)=>`<div class="offer ${o.tier>S.teamTier?'good':''}"><div class="offer-head"><b>${o.team}</b><span>${fmt(o.salary)}/race</span></div><p>${o.series} • Car ${o.car} • Reliability ${o.rel} • ${o.reason}</p><button data-offer="${i}">Accept contract</button></div>`).join(''):'<p class="muted">No active offers. Strong results and reputation attract better teams.</p>';document.querySelectorAll('[data-offer]').forEach(b=>b.onclick=()=>acceptOffer(+b.dataset.offer));const upgrades=[['car','Aerodynamic package','+2 car performance',12+S.series*8],['reliability','Reliability programme','+3 reliability',10+S.series*7],['morale','Team workshop','+8 morale',7+S.series*4]];$('upgrades').innerHTML=upgrades.map(u=>`<div class="upgrade"><h3>${u[1]}</h3><p>${u[2]}</p><button data-upgrade="${u[0]}">${fmt(u[3])}</button></div>`).join('');document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>upgrade(b.dataset.upgrade));$('sponsorName').textContent=S.sponsor?S.sponsor.name:'No sponsor';$('sponsorDetails').innerHTML=S.sponsor?details([['Bonus',fmt(S.sponsor.bonus)+' / race'],['Objective',S.sponsor.objective],['Rounds left',S.sponsor.rounds]]):'<p class="muted">Sign a sponsor for race bonuses, but you must meet its objective.</p>';$('sponsorBtn').textContent=S.sponsor?'Sponsor active':'Find sponsor';$('sponsorBtn').disabled=!!S.sponsor;$('teamDetails').innerHTML=details([['Performance',Math.round(car())],['Reliability',Math.round(reliability())],['Morale',Math.round(S.morale)],['Development bonus',`+${S.carDev} car / +${S.reliabilityDev} rel`]])}
function renderHistory(){$('historyList').innerHTML=S.history.length?S.history.map(h=>`<div class="history-row"><span>${h.text}</span><small>${h.series}<br>Season ${h.season}</small></div>`).join(''):'<p class="muted">Your career history will appear here.</p>'}
function train(type){if(S.qualified||S.trainingLeft<=0)return;if(type==='rest'){S.energy=clamp(S.energy+25,0,100);S.trainingLeft--;status('Recovery session complete. Energy restored.')}else{if(S.money<current().cost)return status('Not enough cash for that training session.');if(S.energy<16)return status('Too fatigued. Use a recovery session.');const gain=rnd(.8,2.1)*(S.morale/85);S.stats[type]=clamp(S.stats[type]+gain,1,99);S.money-=current().cost;S.energy=clamp(S.energy-rnd(8,13),0,100);S.trainingLeft--;status(`${TRAINING[type][0]} improved by ${gain.toFixed(1)}.`)}render()}
function qualify(){if(S.qualified)return;const track=current().tracks[S.round],type=trackType(track);let special=0;if(type==='Street')special=S.stats.racecraft*.07+S.stats.consistency*.05;else if(type==='High speed')special=S.stats.pace*.09+S.stats.fitness*.03;const weatherFactor=S.weather==='Wet'?S.stats.wet*.28:S.weather==='Mixed'?S.stats.wet*.12:0;const playerScore=S.stats.pace*.49+S.stats.consistency*.15+S.stats.fitness*.06+car()*.28+weatherFactor+special+rnd(-4.5,4.5)-(100-S.energy)*.05;const all=[{player:true,name:S.name,score:playerScore,team:team()[0]}];S.field.forEach(d=>{const w=S.weather==='Wet'?d.wet*.24:S.weather==='Mixed'?d.wet*.10:0;all.push({id:d.id,name:d.name,team:'Rival Team',score:d.skill*.57+d.consistency*.12+d.car*.29+w+rnd(-5,5)})});all.sort((a,b)=>b.score-a.score);const pole=all[0].score;all.forEach(d=>d.gap=(pole-d.score)/9.5);S.gridData=all;S.grid=all.findIndex(d=>d.player)+1;S.qualified=true;S.energy=clamp(S.energy-5,0,100);if(S.grid===1){S.seasonPoles++;S.career.poles++;setAchievement('firstPole')}feed([`⏱️ You qualified <strong>P${S.grid}</strong> at ${track}.`,S.weather==='Wet'?'🌧️ Wet conditions heavily rewarded wet-weather skill.':S.weather==='Mixed'?'🌦️ Mixed conditions created a volatile grid.':'☀️ Dry conditions rewarded pace and car performance.'],`Grid P${S.grid}`);status(`Qualified P${S.grid}. Choose race strategy.`);render()}
function feed(lines,badge){$('raceFeed').innerHTML=lines.map(x=>`<div class="feed-item">${x}</div>`).join('');$('resultBadge').textContent=badge}
function simulateRace(){if(!S.qualified)return;S.strategy={start:$('startStrategy').value,tyre:$('tyreStrategy').value,risk:$('riskStrategy').value};const risk={low:-.035,medium:0,high:.055}[S.strategy.risk],startMod={safe:-.4,balanced:0,aggressive:.9}[S.strategy.start],tyreMod={conservative:-.2,balanced:.1,attack:.65}[S.strategy.tyre];const incidents=[];let performance=S.stats.pace*.20+S.stats.racecraft*.29+S.stats.consistency*.16+S.stats.fitness*.10+car()*.25;performance+=(S.weather==='Wet'?S.stats.wet*.22:S.weather==='Mixed'?S.stats.wet*.10:0);performance+=startMod+tyreMod+rnd(-4,4);performance-=(100-S.energy)*.08;performance+=S.morale*.025;
 const start=S.grid;let dnf=false;const errorChance=clamp(.11-S.stats.consistency*.0009+(100-S.energy)*.001+risk+(S.weather==='Wet'?.045:0),.015,.22);const mechChance=clamp((100-reliability())*.0022,.01,.15);if(Math.random()<mechChance){dnf=true;incidents.push('🔧 Mechanical failure forced you to retire.')}else if(Math.random()<errorChance){if(Math.random()<.42){dnf=true;incidents.push('💥 A driving error ended your race.')}else{performance-=rnd(6,12);incidents.push('⚠️ A mistake cost significant time.')}}else{if(S.strategy.start==='aggressive'&&Math.random()<.32)incidents.push('🚀 Aggressive launch gained ground on lap 1.');if(S.strategy.tyre==='attack'&&Math.random()<.28)incidents.push('🔥 Attack strategy delivered strong early pace.');if(S.stats.racecraft>65&&Math.random()<.35)incidents.push('⚔️ Strong wheel-to-wheel racing created overtaking opportunities.');if(S.weather!=='Dry'&&S.stats.wet>62&&Math.random()<.42)incidents.push('🌧️ You were one of the fastest drivers in the changing conditions.')}
 const racers=S.gridData.map(d=>{if(d.player)return{...d,score:dnf?-999:performance};const fd=S.field.find(x=>x.id===d.id);let score=fd.skill*.36+fd.consistency*.17+fd.car*.29+fd.wet*(S.weather==='Wet'?.18:S.weather==='Mixed'?.08:0)+rnd(-7,7);if(Math.random()<(100-current().teams[1][2])*.0012)score-=rnd(12,25);return{...d,score}}).sort((a,b)=>b.score-a.score);let finish=dnf?20:racers.findIndex(x=>x.player)+1;if(dnf){const p=racers.findIndex(x=>x.player);if(p>=0){racers.splice(p,1);racers.push({player:true,name:S.name,score:-999,team:team()[0]})}}
 const pts=dnf?0:(POINTS[finish-1]||0);S.points+=pts;S.standings.player=(S.standings.player||0)+pts;S.career.starts++;S.career.points+=pts;S.career.bestFinish=Math.min(S.career.bestFinish,finish);if(dnf)S.career.dnfs++;if(finish===1){S.career.wins++;S.seasonWins++;setAchievement('firstWin');if(S.series===4)setAchievement('f1win')}if(finish<=3&&!dnf){S.career.podiums++;S.seasonPodiums++}
 racers.forEach((r,i)=>{if(r.player)return;const p=POINTS[i]||0;S.standings[r.id]=(S.standings[r.id]||0)+p;const fd=S.field.find(x=>x.id===r.id);if(i===0)fd.wins=(fd.wins||0)+1});
 let repGain=dnf?-1.5:clamp(6.5-finish*.3+(start-finish)*.3,-1,7);S.rep=clamp(S.rep+repGain,0,100);let income=current().salary*(S.teamTier+1)+(finish<=10?(12-finish)*(.8+S.series*.4):1);if(S.sponsor){income+=S.sponsor.bonus;S.sponsor.rounds--;const success=(S.sponsor.type==='top10'&&finish<=10)||(S.sponsor.type==='podium'&&finish<=3)||(S.sponsor.type==='finish'&&!dnf);if(success){income+=S.sponsor.bonus*.7;incidents.push('💰 Sponsor objective achieved — bonus paid.')}if(S.sponsor.rounds<=0)S.sponsor=null}S.money+=income;S.energy=clamp(S.energy-rnd(14,22)+(S.stats.fitness-50)*.05,0,100);S.morale=clamp(S.morale+(finish<=5?4:finish<=10?1:dnf?-5:-1),35,100);S.results.unshift({track:current().tracks[S.round],start:`P${start}`,finish:dnf?'DNF':`P${finish}`,points:pts,season:S.season});S.results=S.results.slice(0,30);addHistory(`${dnf?'DNF':`P${finish}`} from P${start} — ${current().tracks[S.round]}`,'race');incidents.unshift(`🏁 Finished <strong>${dnf?'DNF':`P${finish}`}</strong> from P${start}${pts?` • ${pts} points`:''}.`);incidents.push(`📈 Reputation ${repGain>=0?'+':''}${repGain.toFixed(1)} • Income ${fmt(income)}.`);feed(incidents,dnf?'DNF':`P${finish}`);$('raceClassification').innerHTML=tableRows(racers.slice(0,10).map((r,i)=>({...r,points:POINTS[i]||0,wins:''})),false);S.round++;S.qualified=false;S.grid=null;S.gridData=[];S.trainingLeft=2;if(S.round>=current().rounds)endSeason();else{pickWeather();maybeOffers();status('Next race weekend ready. Prepare your driver.')}render()}
function endSeason(){const rows=standingsRows();const pos=rows.findIndex(x=>x.player)+1;S.lastSeasonPos=pos;const champ=pos===1;if(champ){S.career.championships++;setAchievement('champion');if(S.series===4)setAchievement('f1champ');addHistory(`🏆 ${current().name} Champion`,'title')}const old=current().name;let promoted=false;if(S.series<4&&pos<=current().promotionPos&&S.rep>=current().promotionRep){S.series++;S.teamTier=0;promoted=true;if(S.series===4)setAchievement('f1');addHistory(`⬆️ Promoted from ${old} to ${current().name}`,'promotion')}else if(!promoted&&S.teamTier<2&&pos<=8){S.teamTier++;addHistory(`📄 Signed by ${current().teams[S.teamTier][0]}`,'contract')}S.season++;S.round=0;S.points=0;S.seasonWins=0;S.seasonPodiums=0;S.seasonPoles=0;S.energy=100;S.morale=clamp(S.morale+8,35,100);S.carDev=Math.max(0,S.carDev-1);S.reliabilityDev=Math.max(0,S.reliabilityDev-1);S.offers=[];generateField();pickWeather();S.trainingLeft=2;S.qualified=false;S.gridData=[];status(promoted?`Promotion secured! Welcome to ${current().name}.`:`New season: ${current().name}. Last season P${pos}.`);feed([`🏁 Season complete — you finished <strong>P${pos}</strong> in the championship.`,promoted?`🎉 Promotion to <strong>${current().name}</strong>.`:`📅 A new season begins with ${team()[0]}.`],'New season');save(true)}
function maybeOffers(){if(S.round<2||Math.random()>.34)return;const choices=[];if(S.teamTier<2&&S.rep>20+S.series*12){const t=S.teamTier+1,tm=current().teams[t];choices.push({series:current().name,tier:t,team:tm[0],car:tm[1],rel:tm[2],salary:current().salary*(t+1),reason:'Your recent performances impressed the team.'})}if(S.series<4&&S.rep>current().promotionRep+8&&Math.random()<.3){const ns=SERIES[S.series+1],tm=ns.teams[0];choices.push({series:ns.name,nextSeries:true,tier:0,team:tm[0],car:tm[1],rel:tm[2],salary:ns.salary,reason:'A higher-category team is willing to take a chance on you.'})}S.offers=choices.slice(0,2)}
function acceptOffer(i){const o=S.offers[i];if(!o)return;if(o.nextSeries){S.series++;S.round=0;S.points=0;S.seasonWins=0;S.seasonPodiums=0;S.seasonPoles=0;S.teamTier=0;generateField();pickWeather();addHistory(`📄 Mid-career promotion: signed by ${o.team}`,'contract');if(S.series===4)setAchievement('f1')}else{S.teamTier=o.tier;addHistory(`📄 Signed contract with ${o.team}`,'contract')}S.offers=[];S.carDev=0;S.reliabilityDev=0;S.morale=78;status(`Contract signed with ${team()[0]}.`);render()}
function upgrade(type){const costs={car:12+S.series*8,reliability:10+S.series*7,morale:7+S.series*4},c=costs[type];if(S.money<c)return status('Not enough cash for that upgrade.');S.money-=c;if(type==='car')S.carDev=clamp(S.carDev+2,0,12);if(type==='reliability')S.reliabilityDev=clamp(S.reliabilityDev+3,0,15);if(type==='morale')S.morale=clamp(S.morale+8,0,100);status('Team upgrade completed.');render()}
function sponsor(){if(S.sponsor)return;const pool=[{name:'Velocity Energy',type:'top10',objective:'Finish top 10',bonus:4+S.series*3,rounds:5},{name:'Apex Data',type:'finish',objective:'Finish the race',bonus:3+S.series*2,rounds:6},{name:'Titan Performance',type:'podium',objective:'Finish on the podium',bonus:7+S.series*4,rounds:4}];S.sponsor=pool[ri(0,pool.length-1)];addHistory(`💼 Sponsor signed: ${S.sponsor.name}`,'sponsor');render()}
function tabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')})}
function newCareerDialog(){const d=$('careerDialog');if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','')}
$('careerForm').addEventListener('submit',e=>{e.preventDefault();const name=$('newDriverName').value.trim()||'Alex Combes';S=fresh(name,$('nationality').value,$('archetype').value);generateField();pickWeather();addHistory('🏁 Career started in Karting','career');$('careerDialog').close();feed(['Your career begins. Train your driver, qualify and race.'],'Career start');status('Choose your preparation, then qualify.');render()});
$('qualifyBtn').onclick=qualify;$('raceBtn').onclick=simulateRace;$('saveBtn').onclick=()=>save(false);$('newCareerBtn').onclick=()=>{if(confirm('Start a completely new career? Your current save will be replaced.'))newCareerDialog()};$('sponsorBtn').onclick=sponsor;tabs();
if(!S){newCareerDialog()}else{ensureSeason();if(!S.weather)pickWeather();feed(['Career loaded. Continue your current race weekend.'],'Ready');render()}
