const SERIES=[
{name:'Karting',rounds:8,laps:18,promotePos:7,promoteRep:28,teams:[['Combes Academy',50,72],['Velocity Juniors',57,77],['Apex Karting',63,82]],tracks:['Melbourne Kart Circuit','Sydney Kart Raceway','Gold Coast Karting','Adelaide Kart Park','Newcastle Kart Circuit','Phillip Island Kart Track','Perth Kart Arena','National Kart Final']},
{name:'Formula 4',rounds:10,laps:24,promotePos:7,promoteRep:46,teams:[['Southern Cross F4',58,74],['Velocity Motorsport',65,79],['Apex Junior Racing',72,84]],tracks:['Phillip Island','Sandown','The Bend','Sydney Motorsport Park','Queensland Raceway','Bathurst Support','Adelaide','Hidden Valley','Taupo','Albert Park']},
{name:'Formula 3',rounds:10,laps:30,promotePos:6,promoteRep:64,teams:[['Nova F3',65,76],['Apex GP',73,82],['Titan Motorsport',81,87]],tracks:['Bahrain','Melbourne','Imola','Monaco','Barcelona','Spielberg','Silverstone','Spa','Monza','Yas Marina']},
{name:'Formula 2',rounds:12,laps:34,promotePos:5,promoteRep:80,teams:[['Nova F2',71,78],['Velocity GP',80,84],['Titan Formula',89,89]],tracks:['Bahrain','Jeddah','Melbourne','Imola','Monaco','Barcelona','Spielberg','Silverstone','Spa','Monza','Baku','Yas Marina']},
{name:'Formula 1',rounds:16,laps:42,promotePos:1,promoteRep:999,teams:[['Phoenix F1',79,80],['Velocity Racing',88,87],['Titan Grand Prix',96,93]],tracks:['Melbourne','Suzuka','Monaco','Barcelona','Spielberg','Silverstone','Spa','Monza','Singapore','Austin','Mexico City','Interlagos','Las Vegas','Qatar','Bahrain','Abu Dhabi']}
];
const FIRST=['Luca','Theo','Mika','Oscar','Hugo','Noah','Felix','Marco','Liam','Jack','Nico','Emil','Leo','Carlos','Pierre','Mateo','Yuki','Daniel','Rafael','Arthur','Oliver','Gabriel','Seb','Maxim','Alexei','James','Callum','Ethan'];
const LAST=['Moretti','Bennett','Keller','Rossi','Dubois','Tanaka','Santos','Muller','Ricci','Lawson','Hart','Vega','Martin','Nakamura','Costa','Bianchi','Novak','Turner','Fischer','Silva','Evans','Reid','Petrov','King','Duran','Mercer','Cole'];
const POINTS=[25,18,15,12,10,8,6,4,2,1], TYRES={Soft:{pace:1.9,wear:1.65},Medium:{pace:.8,wear:1},Hard:{pace:-.2,wear:.68},Intermediate:{pace:-1,wear:1.15}};
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>Math.random()*(b-a)+a,ri=(a,b)=>Math.floor(rnd(a,b+1));
const fmt=n=>'$'+Math.round(n)+'k';
function fresh(name='Alex Combes',nat='Australia',type='balanced'){
 const stats={pace:52,racecraft:51,consistency:52,fitness:50,wet:48,feedback:50}; if(type==='qualifier')stats.pace+=7;if(type==='racer')stats.racecraft+=7;if(type==='rain')stats.wet+=10;if(type==='steady')stats.consistency+=8;
 return {version:3,name,nat,type,series:0,season:1,round:0,points:0,rep:15,cash:30,morale:72,teamTier:0,stats,dev:{aero:0,engine:0,reliability:0,pit:0},practice:3,phase:'practice',qualStage:0,grid:null,field:[],standings:{},results:[],history:[],offers:[],academy:null,rival:null,sponsor:null,career:{starts:0,wins:0,podiums:0,poles:0,points:0,titles:0,dnfs:0,best:99,f1wins:0},race:null,weather:'Dry',forecast:'Stable',sprint:false};
}
let S=load()||fresh();
function cur(){return SERIES[S.series]} function team(){return cur().teams[S.teamTier]} function car(){return clamp(team()[1]+S.dev.aero+S.dev.engine,1,99)} function rel(){return clamp(team()[2]+S.dev.reliability,45,99)}
function save(show=false){localStorage.setItem('roadToF1V3',JSON.stringify(S));if(show)notice('Career saved.')} function load(){try{let x=JSON.parse(localStorage.getItem('roadToF1V3'));return x&&x.version===3?x:null}catch{return null}}
function notice(t){$('notice').textContent=t}
function hist(t){S.history.unshift({t,season:S.season,series:cur().name});S.history=S.history.slice(0,150)}
function weather(){let r=Math.random();S.weather=r<.16?'Wet':r<.34?'Mixed':'Dry';S.forecast=S.weather==='Dry'?(Math.random()<.25?'Rain possible':'Stable'):S.weather==='Wet'?'Rain likely':'Changeable'}
function makeField(){S.field=[];let used=new Set([S.name]),base=49+S.series*8;for(let i=0;i<19;i++){let n;do n=FIRST[ri(0,FIRST.length-1)]+' '+LAST[ri(0,LAST.length-1)];while(used.has(n));used.add(n);S.field.push({id:'d'+i,name:n,skill:clamp(base+rnd(-8,10),35,96),wet:clamp(base+rnd(-12,12),30,98),cons:clamp(base+rnd(-8,10),35,97),car:clamp(base+rnd(-7,9),40,96),points:0,wins:0})}S.rival=S.field.sort((a,b)=>b.skill-a.skill)[Math.min(3,S.series)]?.id||'d0'}
function ensure(){if(!S.field||S.field.length!==19)makeField();if(!S.weather)weather();if(S.sprint===undefined)S.sprint=false}
function trackType(name){if(/Monaco|Singapore|Baku|Jeddah|Las Vegas|Adelaide/.test(name))return'Street';if(/Monza|Spielberg|Bahrain/.test(name))return'Power';if(/Suzuka|Silverstone|Spa|Phillip/.test(name))return'High speed';return'Balanced'}
function overall(){let x=S.stats;return Math.round(x.pace*.25+x.racecraft*.22+x.consistency*.18+x.fitness*.12+x.wet*.11+x.feedback*.12)}
function render(){ensure();let c=cur(),track=c.tracks[S.round]||'Season complete';$('hudDriver').textContent=S.name;$('hudSeries').textContent=c.name;$('hudSeason').textContent=S.season;$('hudRound').textContent=(S.round+1)+'/'+c.rounds;$('hudPoints').textContent=S.points;$('hudRep').textContent=Math.round(S.rep);$('hudCash').textContent=fmt(S.cash);$('trackTitle').textContent=track;$('trackMeta').textContent=trackType(track)+' circuit • '+c.laps+' laps'+(S.sprint?' • Sprint weekend':'');$('weatherLabel').textContent=S.weather==='Dry'?'☀️ Dry':S.weather==='Wet'?'🌧️ Wet':'🌦️ Mixed';$('weatherForecast').textContent=S.forecast;$('practiceLeft').textContent=S.practice+' sessions left';
 renderPhases();renderTraining();renderDriver();renderStandings();renderTeam();renderHistory();renderRace();renderQual();
}
function renderPhases(){let phases=['Practice',S.series===4?'Q1/Q2/Q3':'Qualifying',S.sprint?'Sprint':'Race','Race'];if(!S.sprint)phases=['Practice',S.series===4?'Q1/Q2/Q3':'Qualifying','Race'];let current=S.phase;let done={practice:['qualifying','sprint','race','finished'].includes(current),qualifying:['sprint','race','finished'].includes(current),sprint:['race','finished'].includes(current),race:current==='finished'};$('phaseStrip').innerHTML=phases.map(p=>{let key=p.startsWith('Q')||p==='Qualifying'?'qualifying':p.toLowerCase();return`<span class="phase ${done[key]?'done':''} ${current===key?'active':''}">${done[key]?'✓ ':''}${p}</span>`}).join('')}
function renderTraining(){let items=[['pace','🏎️ Pace','Raw speed'],['racecraft','⚔️ Racecraft','Overtaking/defence'],['consistency','🎯 Consistency','Fewer mistakes'],['fitness','💪 Fitness','Race endurance'],['wet','🌧️ Wet skill','Rain pace'],['feedback','🧠 Feedback','Setup/development']];$('trainingGrid').innerHTML=items.map(x=>`<button data-train="${x[0]}" ${S.phase!=='practice'||S.practice<=0?'disabled':''}>${x[1]}<small>${x[2]}</small></button>`).join('');document.querySelectorAll('[data-train]').forEach(b=>b.onclick=()=>train(b.dataset.train))}
function train(k){if(S.practice<=0)return;let cost=1+S.series*3;if(S.cash<cost)return notice('Not enough cash.');S.cash-=cost;S.stats[k]=clamp(S.stats[k]+rnd(1,2.6),0,99);S.practice--;if(S.practice===0){S.phase='qualifying';notice('Practice complete. Qualifying is ready.')}else notice('Session complete.');render();save()}
function qualScore(d,isPlayer){let wet=S.weather==='Wet'?.22:S.weather==='Mixed'?.1:0;if(isPlayer)return S.stats.pace*.43+S.stats.consistency*.12+car()*.34+S.stats.wet*wet+S.morale*.02+rnd(-4.5,4.5);return d.skill*.52+d.cons*.12+d.car*.31+d.wet*wet+rnd(-5,5)}
function qualSession(){if(S.phase!=='qualifying')return;let all=[{player:true,name:S.name,score:qualScore(null,true)},...S.field.map(d=>({...d,score:qualScore(d,false)}))].sort((a,b)=>b.score-a.score);if(S.series===4){S.qualStage++;let cut=S.qualStage===1?15:S.qualStage===2?10:20;let p=all.findIndex(x=>x.player)+1;if((S.qualStage===1&&p>15)||(S.qualStage===2&&p>10)||S.qualStage===3){S.grid=p;finishQual(all)}else{notice(`Advanced to Q${S.qualStage+1}.`);$('qualResults').innerHTML=table(all.slice(0,cut),p);renderQual();save();return}}else{S.grid=all.findIndex(x=>x.player)+1;finishQual(all)} }
function finishQual(all){if(S.grid===1){S.career.poles++;hist('⏱️ Pole position at '+cur().tracks[S.round])}S.phase=S.sprint?'sprint':'race';$('qualResults').innerHTML=table(all,S.grid);notice(`Qualified P${S.grid}. Choose your race strategy.`);render();save()}
function table(all,p){return'<table><tr><th>Pos</th><th>Driver</th></tr>'+all.map((d,i)=>`<tr class="${d.player?'you':''}"><td>P${i+1}</td><td>${d.name}</td></tr>`).join('')+'</table>'}
function renderQual(){$('qualTitle').textContent=S.series===4?`F1 Qualifying ${S.qualStage?'- Q'+(S.qualStage+1):'- Q1'}`:'Qualifying';$('qualBadge').textContent=S.grid?'P'+S.grid:(S.phase==='qualifying'?'Ready':'Not run');$('gridBadge').textContent=S.grid?'Grid P'+S.grid:'No grid';$('qualBtn').disabled=S.phase!=='qualifying';$('raceBtn').disabled=!(S.phase==='race'||S.phase==='sprint')||!!S.race;$('raceBtn').textContent=S.phase==='sprint'?'Start sprint':'Start race'}
function startRace(){if(!(S.phase==='race'||S.phase==='sprint')||!S.grid)return;let laps=S.phase==='sprint'?Math.max(10,Math.round(cur().laps*.32)):cur().laps;let tyre=$('startTyre').value;if(S.weather==='Wet'&&tyre!=='Intermediate')tyre='Intermediate';let racers=[{player:true,id:'player',name:S.name,pos:S.grid,skill:S.stats.pace*.25+S.stats.racecraft*.3+S.stats.consistency*.16+car()*.29,wet:S.stats.wet,cons:S.stats.consistency,car:car(),tyre,wear:0,gap:0,damage:0,pits:0,dnf:false,totalTime:(S.grid-1)*.18,lastLap:null},...S.field.map((d,i)=>{let pos=i+1+(i>=S.grid?1:0);return{id:d.id,name:d.name,pos,skill:d.skill*.48+d.cons*.15+d.car*.37,wet:d.wet,cons:d.cons,car:d.car,tyre:S.weather==='Wet'?'Intermediate':['Soft','Medium','Hard'][ri(0,2)],wear:0,gap:0,damage:0,pits:0,dnf:false,totalTime:(pos-1)*.18,lastLap:null}})];racers.sort((a,b)=>a.pos-b.pos);S.race={lap:0,laps,racers,sc:0,red:false,weather:S.weather,playerFuel:100,playerERS:100,feed:[],pending:null,sprint:S.phase==='sprint',baseLap:[55,96,93,92,90][S.series]||90};feed('🏁 '+(S.phase==='sprint'?'Sprint':'Race')+' started from P'+S.grid+'.');$('raceBtn').disabled=true;renderRace();save()}
function advance(n=1){if(!S.race)return;for(let i=0;i<n&&S.race&&S.race.lap<S.race.laps;i++){if(S.race.pending)break;simLap()}renderRace();render();save()}
function simLap(){let r=S.race;r.lap++;if(r.sc>0)r.sc--;let changeChance=S.forecast==='Rain possible'||S.forecast==='Changeable'?0.025:.006;if(Math.random()<changeChance){r.weather=r.weather==='Dry'?'Wet':'Dry';feed('🌦️ Weather change: '+r.weather+' conditions.');radio('Weather change','Pit for suitable tyres?',[['Pit now','pit'],['Stay out','stay']]);}
 let risk={Low:-.5,Medium:0,High:.7}[$('risk').value],ers={Save:-.35,Balanced:0,Attack:.7}[$('ers').value],fuel={Conserve:-.3,Balanced:0,Push:.55}[$('fuel').value];r.playerERS=clamp(r.playerERS+( $('ers').value==='Save'?3:$('ers').value==='Attack'?-5:0),0,100);r.playerFuel=clamp(r.playerFuel-(100/r.laps)*( $('fuel').value==='Push'?1.08:$('fuel').value==='Conserve'?.92:1),0,100);
 r.racers.forEach(d=>{if(d.dnf)return;if(!Number.isFinite(d.totalTime))d.totalTime=(d.pos-1)*.18;let t=TYRES[d.tyre]||TYRES.Medium;d.wear+=t.wear*(r.sc?0.35:1)*(d.player?1:rnd(.9,1.1));let tyrePenalty=Math.max(0,d.wear-68)*.045;let wetFit=r.weather==='Wet'?(d.tyre==='Intermediate'?2.2:-3.8)+(d.wet-50)*.045:(d.tyre==='Intermediate'?-3.2:0);let p=d.skill+t.pace-tyrePenalty+wetFit+rnd(-2.1,2.1)-d.damage*.12;if(d.player)p+=risk+ers+fuel;d.lapPace=p;let lapNoise=r.sc?rnd(-.08,.08):rnd(-.38,.38);let lapTime=(r.baseLap||90)+(82-p)*.055+lapNoise;if(r.weather==='Wet')lapTime+=8.5;if(r.sc)lapTime=(r.baseLap||90)+17+rnd(-.15,.15);let err=clamp(.003+(65-d.cons)*.00045+(d.player&&$('risk').value==='High'?.008:0)+(r.weather==='Wet'?.005:0),.001,.035);if(Math.random()<err){if(Math.random()<.28){d.dnf=true;d.lastLap=null;feed('💥 '+d.name+' crashed and retired.');if(Math.random()<.45){r.sc=ri(2,4);feed('🚨 Safety Car deployed.')}}else{let lost=rnd(2.5,9);d.damage=clamp(d.damage+rnd(4,18),0,60);lapTime+=lost;feed('⚠️ '+d.name+' made a mistake and lost '+lost.toFixed(1)+'s.')}}let mech=(100-(d.player?rel():Math.min(96,d.car+8)))*.00035;if(Math.random()<mech){d.dnf=true;d.lastLap=null;feed('🔧 '+d.name+' retired with a mechanical failure.')}if(!d.dnf){d.lastLap=Math.max(1,lapTime);d.totalTime+=d.lastLap}});
 let alive=r.racers.filter(x=>!x.dnf).sort((a,b)=>a.totalTime-b.totalTime);if(r.sc&&alive.length){let lead=alive[0].totalTime;alive.forEach((d,i)=>d.totalTime=lead+i*rnd(.18,.42))}let dead=r.racers.filter(x=>x.dnf).sort((a,b)=>(a.pos||99)-(b.pos||99));r.racers=[...alive,...dead];let leader=alive[0];r.racers.forEach((d,i)=>{d.pos=i+1;d.gap=d.dnf?null:(leader?Math.max(0,d.totalTime-leader.totalTime):0)});
 let p=r.racers.find(x=>x.player);if(p&&p.wear>75&&!r.pending)radio('Tyres fading',`${p.tyre} wear is ${Math.round(p.wear)}%. Pit?`,[['Pit','pit'],['Stay out','stay']]);if(r.lap===Math.round(r.laps*.55)&&!r.pending&&Math.random()<.45)radio('Strategy call','Undercut opportunity. Push and pit next lap?',[['Box','pit'],['Extend','stay']]);if(r.lap===Math.round(r.laps*.7)&&Math.random()<.08){r.red=true;feed('🟥 Red flag. Race suspended and field reset.');let alive=r.racers.filter(d=>!d.dnf);if(alive.length){let lead=alive[0].totalTime;alive.forEach((d,i)=>{d.totalTime=lead+i*.25;d.gap=i*.25})}}
 if(r.lap>=r.laps)finishRace()}
function radio(title,text,choices){if(S.race.pending)return;S.race.pending={title,text,choices}}
function chooseRadio(action){let r=S.race,p=r.racers.find(x=>x.player);if(action==='pit'){p.pits++;p.wear=0;p.tyre=r.weather==='Wet'?'Intermediate':(p.tyre==='Soft'?'Medium':'Hard');let pitLoss=Math.max(14,22+S.series*1.2-S.dev.pit*.65+rnd(-.8,.8));p.totalTime=(Number.isFinite(p.totalTime)?p.totalTime:0)+pitLoss;feed('🔧 Pit stop: fitted '+p.tyre+' tyres • '+pitLoss.toFixed(1)+'s pit-lane loss.');let alive=r.racers.filter(x=>!x.dnf).sort((a,b)=>a.totalTime-b.totalTime),dead=r.racers.filter(x=>x.dnf);r.racers=[...alive,...dead];let leader=alive[0];r.racers.forEach((d,i)=>{d.pos=i+1;d.gap=d.dnf?null:(leader?Math.max(0,d.totalTime-leader.totalTime):0)})}else feed('📻 You stayed out.');r.pending=null;renderRace()}
function finishRace(){let r=S.race,p=r.racers.find(x=>x.player),finish=p.pos,dnf=p.dnf,pts=dnf?0:(r.sprint?[8,7,6,5,4,3,2,1][finish-1]||0:POINTS[finish-1]||0);S.points+=pts;S.career.points+=pts;if(!r.sprint){S.career.starts++;if(dnf)S.career.dnfs++;if(finish===1){S.career.wins++;if(S.series===4)S.career.f1wins++}if(finish<=3&&!dnf)S.career.podiums++;S.career.best=Math.min(S.career.best,finish)}S.standings.player=(S.standings.player||0)+pts;r.racers.forEach((d,i)=>{if(d.player)return;let q=r.sprint?([8,7,6,5,4,3,2,1][i]||0):(POINTS[i]||0);S.standings[d.id]=(S.standings[d.id]||0)+q});S.rep=clamp(S.rep+(dnf?-1:Math.max(-.5,6-finish*.28)),0,100);S.cash+=3+S.series*6+(finish<=10?11-finish:0);S.results.unshift({season:S.season,track:cur().tracks[S.round],kind:r.sprint?'Sprint':'Race',finish:dnf?'DNF':'P'+finish,points:pts});hist(`${r.sprint?'Sprint':'Race'} ${dnf?'DNF':'P'+finish} at ${cur().tracks[S.round]}`);feed(`🏁 Finished ${dnf?'DNF':'P'+finish} • ${pts} points.`);if(r.sprint){S.race=null;S.phase='race';notice('Sprint complete. Main race ready.');render();return}S.race=null;S.round++;S.grid=null;S.qualStage=0;S.practice=3;S.phase='practice';if(S.round>=cur().rounds)endSeason();else{weather();S.sprint=S.series===4&&Math.random()<.25;maybeOffer();notice('Next race weekend ready.')}render();save()}
function endSeason(){let rows=standingRows(),pos=rows.findIndex(x=>x.player)+1;if(pos===1){S.career.titles++;hist('🏆 '+cur().name+' champion')}if(S.series<4&&pos<=cur().promotePos&&S.rep>=cur().promoteRep){S.series++;S.teamTier=0;hist('⬆️ Promoted to '+cur().name);if(!S.academy&&S.series>=2)S.academy=['Velocity Academy','Titan Junior Programme','Apex Driver Academy'][ri(0,2)]}else if(pos<=8&&S.teamTier<2){S.teamTier++;hist('📄 Signed by '+team()[0])}S.season++;S.round=0;S.points=0;S.standings={};S.dev.aero=Math.max(0,S.dev.aero-1);S.dev.engine=Math.max(0,S.dev.engine-1);makeField();weather();S.sprint=S.series===4&&Math.random()<.25;S.practice=3;S.phase='practice';S.grid=null;notice('New season begins.');save()}
function lapTimeFmt(sec){if(!Number.isFinite(sec))return'—';let m=Math.floor(sec/60),s=sec-m*60;return m+':'+s.toFixed(3).padStart(6,'0')}
function gapFmt(d,r){if(d.dnf)return'OUT';if(d.pos===1)return'LEADER';let gap=Number.isFinite(d.gap)?d.gap:0,base=r.baseLap||90;if(gap>=base){let laps=Math.floor(gap/base);return'+'+laps+' Lap'+(laps>1?'s':'')}return'+'+gap.toFixed(3)+'s'}
function pitTable(){let r=S.race;return'<table><tr><th>Pos</th><th>Driver</th><th>Gap</th><th>Last lap</th><th>Tyre</th><th>Wear</th><th>Status</th></tr>'+r.racers.slice(0,20).map(d=>`<tr class="${d.player?'you':''}"><td>P${d.pos}</td><td>${d.name}</td><td><strong>${gapFmt(d,r)}</strong></td><td>${lapTimeFmt(d.lastLap)}</td><td>${d.tyre}</td><td>${Math.round(d.wear)}%</td><td>${d.dnf?'OUT':d.damage>15?'Damage':'Running'}</td></tr>`).join('')+'</table>'}
function renderRace(){let r=S.race;if(!r){$('raceStatus').textContent='Race not started';$('lapBadge').textContent='Lap —';$('timing').innerHTML='Start the race to see live timing.';$('lapBtn').disabled=$('fiveBtn').disabled=$('autoBtn').disabled=true;$('radioBox').classList.add('hidden');return}$('raceStatus').textContent=(r.sc?'Safety Car • ':'')+(r.weather==='Wet'?'Wet':'Dry')+' race';$('lapBadge').textContent=`Lap ${r.lap}/${r.laps}`;$('timing').innerHTML=pitTable();$('lapBtn').disabled=$('fiveBtn').disabled=$('autoBtn').disabled=!!r.pending;if(r.pending){$('radioBox').classList.remove('hidden');$('radioBox').innerHTML=`<strong>📻 ${r.pending.title}</strong><div>${r.pending.text}</div><div class="choices">${r.pending.choices.map(c=>`<button data-radio="${c[1]}">${c[0]}</button>`).join('')}</div>`;document.querySelectorAll('[data-radio]').forEach(b=>b.onclick=()=>chooseRadio(b.dataset.radio))}else $('radioBox').classList.add('hidden')}
function feed(t){let box=$('feed'),d=document.createElement('div');d.className='feeditem';d.textContent=t;box.prepend(d);while(box.children.length>30)box.removeChild(box.lastChild)}
function standingRows(){let rows=[{player:true,name:S.name,points:S.standings.player||S.points},...S.field.map(d=>({id:d.id,name:d.name,points:S.standings[d.id]||0}))];return rows.sort((a,b)=>b.points-a.points)}
function renderStandings(){let rows=standingRows();$('standingsTable').innerHTML='<table><tr><th>Pos</th><th>Driver</th><th>Points</th></tr>'+rows.map((d,i)=>`<tr class="${d.player?'you':''}"><td>${i+1}</td><td>${d.name}</td><td>${d.points}</td></tr>`).join('')+'</table>';$('seasonResults').innerHTML='<table><tr><th>Round</th><th>Session</th><th>Result</th><th>Pts</th></tr>'+S.results.filter(x=>x.season===S.season).map(x=>`<tr><td>${x.track}</td><td>${x.kind}</td><td>${x.finish}</td><td>${x.points}</td></tr>`).join('')+'</table>'}
function renderDriver(){let labels={pace:'Pace',racecraft:'Racecraft',consistency:'Consistency',fitness:'Fitness',wet:'Wet skill',feedback:'Feedback'};$('driverStats').innerHTML=`<p><strong>Overall ${overall()}</strong> • Morale ${Math.round(S.morale)}%</p>`+Object.entries(S.stats).map(([k,v])=>`<div class="statrow"><div class="statline"><span>${labels[k]}</span><strong>${Math.round(v)}</strong></div><div class="bar"><span style="width:${v}%"></span></div></div>`).join('');$('ladder').innerHTML=SERIES.map((x,i)=>`<div class="ladderRow ${i===S.series?'current':''}">${i<S.series?'✓':i===S.series?'🏁':'○'} ${x.name}</div>`).join('');$('academyBox').innerHTML=S.academy?`<div class="contract">🎓 ${S.academy}<br><span class="muted">Boosts your reputation with stronger teams.</span></div>`:'<div class="muted">No academy contract yet.</div>';let rv=S.field.find(x=>x.id===S.rival);$('rivalBox').innerHTML=rv?`<div class="contract">⚔️ ${rv.name}<br><span class="muted">Your benchmark this season.</span></div>`:'—'}
function upgrade(k){let cost=12+S.series*8+S.dev[k]*4;if(S.cash<cost)return notice('Not enough cash for upgrade.');S.cash-=cost;S.dev[k]=clamp(S.dev[k]+2,0,14);notice(k+' upgrade completed.');hist('🔧 Team upgraded '+k);render();save()}
function maybeOffer(){if(Math.random()>.35)return;S.offers=[];if(S.teamTier<2&&S.rep>25+S.series*11){let t=S.teamTier+1;S.offers.push({team:cur().teams[t][0],tier:t,series:S.series})}if(S.series<4&&S.rep>cur().promoteRep+8&&Math.random()<.35)S.offers.push({team:SERIES[S.series+1].teams[0][0],tier:0,series:S.series+1})}
function acceptOffer(i){let o=S.offers[i];if(!o)return;if(o.series>S.series){S.series=o.series;S.round=0;S.points=0;S.standings={};makeField();weather()}S.teamTier=o.tier;S.offers=[];hist('📄 Contract signed: '+o.team);notice('Signed with '+o.team);render();save()}
function sponsor(){if(S.sponsor)return;S.sponsor={name:['Velocity Energy','Apex Data','Titan Performance'][ri(0,2)],rounds:6,bonus:4+S.series*3};hist('💼 Sponsor signed: '+S.sponsor.name);render();save()}
function renderTeam(){$('teamName').textContent=team()[0];$('teamInfo').innerHTML=`<p>Car performance <strong>${Math.round(car())}</strong>/100 • Reliability <strong>${Math.round(rel())}</strong>/100</p><p>Aero +${S.dev.aero} • Power +${S.dev.engine} • Reliability +${S.dev.reliability} • Pit crew +${S.dev.pit}</p>`;document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>upgrade(b.dataset.up));$('contracts').innerHTML=S.offers.length?S.offers.map((o,i)=>`<div class="contract"><strong>${o.team}</strong><br><span class="muted">${SERIES[o.series].name}</span><br><button data-offer="${i}">Accept contract</button></div>`).join(''):'<div class="muted">No active offers.</div>';document.querySelectorAll('[data-offer]').forEach(b=>b.onclick=()=>acceptOffer(+b.dataset.offer));$('sponsorBox').innerHTML=S.sponsor?`<div class="sponsor">💼 ${S.sponsor.name} • ${S.sponsor.rounds} rounds remaining</div>`:'<button id="sponsorBtn">Find sponsor</button>';if($('sponsorBtn'))$('sponsorBtn').onclick=sponsor}
function renderHistory(){let c=S.career;$('careerStats').innerHTML=`<table><tr><th>Starts</th><td>${c.starts}</td></tr><tr><th>Wins</th><td>${c.wins}</td></tr><tr><th>Podiums</th><td>${c.podiums}</td></tr><tr><th>Poles</th><td>${c.poles}</td></tr><tr><th>Titles</th><td>${c.titles}</td></tr><tr><th>F1 wins</th><td>${c.f1wins}</td></tr><tr><th>Career points</th><td>${c.points}</td></tr><tr><th>DNFs</th><td>${c.dnfs}</td></tr></table>`;$('historyList').innerHTML=S.history.length?S.history.map(h=>`<div><strong>S${h.season} • ${h.series}</strong><br>${h.t}</div>`).join(''):'<div class="muted">No history yet.</div>'}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});$('qualBtn').onclick=qualSession;$('raceBtn').onclick=startRace;$('lapBtn').onclick=()=>advance(1);$('fiveBtn').onclick=()=>advance(5);$('autoBtn').onclick=()=>{for(let i=0;i<10&&S.race&&!S.race.pending;i++)simLap();renderRace();render();save()};$('saveBtn').onclick=()=>save(true);$('newBtn').onclick=()=>{if(confirm('Start a new career and replace your save?'))$('newDialog').showModal()};$('newForm').onsubmit=e=>{e.preventDefault();S=fresh($('driverName').value.trim()||'Alex Combes',$('nationality').value,$('archetype').value);makeField();weather();hist('🏁 Career started in Karting');$('newDialog').close();notice('Career started. Begin practice.');render();save()}}
ensure();bind();if(!localStorage.getItem('roadToF1V3'))$('newDialog').showModal();render();
