const SERIES=[
{name:'Karting',rounds:8,laps:18,promotePos:7,promoteRep:28,sl:0,teams:[['Combes Academy',46,70],['Velocity Juniors',58,78],['Apex Karting',70,85]],tracks:['Melbourne Kart Circuit','Sydney Kart Raceway','Gold Coast Karting','Adelaide Kart Park','Newcastle Kart Circuit','Phillip Island Kart Track','Perth Kart Arena','National Kart Final']},
{name:'Formula 4',rounds:10,laps:24,promotePos:7,promoteRep:46,sl:12,teams:[['Southern Cross F4',52,72],['Velocity Motorsport',66,80],['Apex Junior Racing',80,87]],tracks:['Phillip Island','Sandown','The Bend','Sydney Motorsport Park','Queensland Raceway','Bathurst Support','Adelaide','Hidden Valley','Taupo','Albert Park']},
{name:'Formula 3',rounds:10,laps:30,promotePos:6,promoteRep:64,sl:18,teams:[['Nova F3',58,74],['Apex GP',74,83],['Titan Motorsport',88,90]],tracks:['Bahrain','Melbourne','Imola','Monaco','Barcelona','Spielberg','Silverstone','Spa','Monza','Yas Marina']},
{name:'Formula 2',rounds:12,laps:34,promotePos:5,promoteRep:80,sl:30,teams:[['Nova F2',64,76],['Velocity GP',80,85],['Titan Formula',94,92]],tracks:['Bahrain','Jeddah','Melbourne','Imola','Monaco','Barcelona','Spielberg','Silverstone','Spa','Monza','Baku','Yas Marina']},
{name:'Formula 1',rounds:16,laps:42,promotePos:1,promoteRep:999,sl:40,teams:[['Phoenix F1',72,79],['Velocity Racing',86,88],['Titan Grand Prix',98,95]],tracks:['Melbourne','Suzuka','Monaco','Barcelona','Spielberg','Silverstone','Spa','Monza','Singapore','Austin','Mexico City','Interlagos','Las Vegas','Qatar','Bahrain','Abu Dhabi']}
];
const FIRST=['Luca','Theo','Mika','Oscar','Hugo','Noah','Felix','Marco','Liam','Jack','Nico','Emil','Leo','Carlos','Pierre','Mateo','Yuki','Daniel','Rafael','Arthur','Oliver','Gabriel','Seb','Maxim','Alexei','James','Callum','Ethan'];
const LAST=['Moretti','Bennett','Keller','Rossi','Dubois','Tanaka','Santos','Muller','Ricci','Lawson','Hart','Vega','Martin','Nakamura','Costa','Bianchi','Novak','Turner','Fischer','Silva','Evans','Reid','Petrov','King','Duran','Mercer','Cole'];
const POINTS=[25,18,15,12,10,8,6,4,2,1];
const TYRES={Soft:{pace:1.9,wear:6.8,life:14},Medium:{pace:.8,wear:4.5,life:22},Hard:{pace:-.2,wear:3.1,life:32},Intermediate:{pace:-1,wear:5.3,life:19}};
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>Math.random()*(b-a)+a,ri=(a,b)=>Math.floor(rnd(a,b+1));
const fmt=n=>'$'+Math.round(n)+'k';
function fresh(name='Alex Combes',nat='Australia',type='balanced'){
 const stats={pace:52,racecraft:51,consistency:52,fitness:50,wet:48,feedback:50};if(type==='qualifier')stats.pace+=7;if(type==='racer')stats.racecraft+=7;if(type==='rain')stats.wet+=10;if(type==='steady')stats.consistency+=8;
 return {version:4,name,nat,type,series:0,season:1,round:0,points:0,rep:15,cash:30,morale:72,teamTier:0,stats,dev:{aero:0,engine:0,reliability:0,pit:0},practice:3,phase:'practice',qualStage:0,grid:null,field:[],standings:{},results:[],history:[],offers:[],academy:null,academyOffers:[],rival:null,teammate:null,sponsor:null,superLicence:0,market:[],qualHistory:[],lastQual:null,lastAnalysis:null,career:{starts:0,wins:0,podiums:0,poles:0,points:0,titles:0,dnfs:0,best:99,f1wins:0,fastestLaps:0,teammateWins:0,teammateLosses:0},race:null,weather:'Dry',forecast:'Stable',sprint:false};
}
let S=load()||fresh();
function cur(){return SERIES[S.series]}function team(){return cur().teams[S.teamTier]}function car(){return clamp(team()[1]+S.dev.aero+S.dev.engine,1,99)}function rel(){return clamp(team()[2]+S.dev.reliability,45,99)}
function save(show=false){localStorage.setItem('roadToF1V4',JSON.stringify(S));if(show)notice('Career saved.')} 
function load(){try{let x=JSON.parse(localStorage.getItem('roadToF1V4'));if(x&&x.version===4)return x;let old=JSON.parse(localStorage.getItem('roadToF1V33'));if(old){let n={...fresh(old.name,old.nat,old.type),...old,version:4};n.superLicence=old.superLicence||Math.min(39,old.series*8);n.market=[];n.qualHistory=[];n.lastQual=null;n.lastAnalysis=null;n.academyOffers=[];n.career={...fresh().career,...old.career};n.race=null;n.phase=old.grid?'race':(old.phase==='finished'?'practice':old.phase);return n}return null}catch{return null}}
function notice(t){$('notice').textContent=t}function hist(t){S.history.unshift({t,season:S.season,series:cur().name});S.history=S.history.slice(0,180)}
function weather(){let r=Math.random();S.weather=r<.16?'Wet':r<.34?'Mixed':'Dry';S.forecast=S.weather==='Dry'?(Math.random()<.25?'Rain possible':'Stable'):S.weather==='Wet'?'Rain likely':'Changeable'}
function makeField(){S.field=[];let used=new Set([S.name]),base=49+S.series*8;for(let i=0;i<19;i++){let n;do n=FIRST[ri(0,FIRST.length-1)]+' '+LAST[ri(0,LAST.length-1)];while(used.has(n));used.add(n);let teamTier=ri(0,2),teamPerf=cur().teams[teamTier][1];S.field.push({id:'d'+i,name:n,skill:clamp(base+rnd(-14,14),30,98),wet:clamp(base+rnd(-16,16),25,99),cons:clamp(base+rnd(-12,13),30,98),car:clamp(teamPerf+rnd(-2.5,2.5),35,99),points:0,wins:0,teamTier})}S.spreadV42=true;S.rival=[...S.field].sort((a,b)=>b.skill-a.skill)[Math.min(3,S.series)]?.id||'d0';S.teammate=[...S.field].sort((a,b)=>Math.abs(b.skill-overall())-Math.abs(a.skill-overall()))[0]?.id||'d0'}
function ensure(){if(!S.field||S.field.length!==19)makeField();if(!S.spreadV42&&S.field?.length===19){let base=49+S.series*8;S.field.forEach(d=>{d.teamTier=clamp(d.teamTier??ri(0,2),0,2);let teamPerf=cur().teams[d.teamTier][1];d.skill=clamp(base+(d.skill-base)*1.45+rnd(-1.5,1.5),30,98);d.wet=clamp(base+(d.wet-base)*1.25,25,99);d.cons=clamp(base+(d.cons-base)*1.3,30,98);d.car=clamp(teamPerf+rnd(-2,2),35,99)});S.spreadV42=true}if(!S.weather)weather();if(S.sprint===undefined)S.sprint=false;if(!S.career.fastestLaps)S.career.fastestLaps=0;if(!S.market)S.market=[];if(!S.academyOffers)S.academyOffers=[]}
function trackType(name){if(/Monaco|Singapore|Baku|Jeddah|Las Vegas|Adelaide/.test(name))return'Street';if(/Monza|Spielberg|Bahrain/.test(name))return'Power';if(/Suzuka|Silverstone|Spa|Phillip/.test(name))return'High speed';return'Balanced'}
function overall(){let x=S.stats;return Math.round(x.pace*.25+x.racecraft*.22+x.consistency*.18+x.fitness*.12+x.wet*.11+x.feedback*.12)}
function render(){ensure();let c=cur(),track=c.tracks[S.round]||'Season complete';$('hudDriver').textContent=S.name;$('hudSeries').textContent=c.name;$('hudSeason').textContent=S.season;$('hudRound').textContent=(S.round+1)+'/'+c.rounds;$('hudPoints').textContent=S.points;$('hudRep').textContent=Math.round(S.rep);$('hudCash').textContent=fmt(S.cash);$('hudSL').textContent=Math.round(S.superLicence)+'/40';$('trackTitle').textContent=track;$('trackMeta').textContent=trackType(track)+' circuit • '+c.laps+' laps'+(S.sprint?' • Sprint weekend':'');$('weatherLabel').textContent=S.weather==='Dry'?'☀️ Dry':S.weather==='Wet'?'🌧️ Wet':'🌦️ Mixed';$('weatherForecast').textContent=S.forecast;$('practiceLeft').textContent=S.practice+' sessions left';renderPhases();renderTraining();renderDriver();renderStandings();renderTeam();renderHistory();renderRace();renderQual();}
function renderPhases(){let phases=['Practice',S.series===4?'Q1/Q2/Q3':'Qualifying',S.sprint?'Sprint':'Race','Race'];if(!S.sprint)phases=['Practice',S.series===4?'Q1/Q2/Q3':'Qualifying','Race'];let current=S.phase;let done={practice:['qualifying','sprint','race','finished'].includes(current),qualifying:['sprint','race','finished'].includes(current),sprint:['race','finished'].includes(current),race:current==='finished'};$('phaseStrip').innerHTML=phases.map(p=>{let key=p.startsWith('Q')||p==='Qualifying'?'qualifying':p.toLowerCase();return`<span class="phase ${done[key]?'done':''} ${current===key?'active':''}">${done[key]?'✓ ':''}${p}</span>`}).join('')}
function renderTraining(){let items=[['pace','🏎️ Pace','Raw speed'],['racecraft','⚔️ Racecraft','Overtaking/defence'],['consistency','🎯 Consistency','Fewer mistakes'],['fitness','💪 Fitness','Race endurance'],['wet','🌧️ Wet skill','Rain pace'],['feedback','🧠 Feedback','Setup/development']];$('trainingGrid').innerHTML=items.map(x=>`<button data-train="${x[0]}" ${S.phase!=='practice'||S.practice<=0?'disabled':''}>${x[1]}<small>${x[2]}</small></button>`).join('');document.querySelectorAll('[data-train]').forEach(b=>b.onclick=()=>train(b.dataset.train))}
function train(k){if(S.practice<=0)return;let cost=1+S.series*3;if(S.cash<cost)return notice('Not enough cash.');S.cash-=cost;S.stats[k]=clamp(S.stats[k]+rnd(1,2.6),0,99);S.practice--;if(S.practice===0){S.phase='qualifying';notice('Practice complete. Qualifying is ready.')}else notice('Session complete.');render();save()}
function baseQualLap(){return [52,94,91,90,88][S.series]||90}
function qualAbility(d,isPlayer){let wet=S.weather==='Wet'?.22:S.weather==='Mixed'?.1:0;if(isPlayer)return S.stats.pace*.43+S.stats.consistency*.12+car()*.34+S.stats.wet*wet+S.morale*.02;return d.skill*.52+d.cons*.12+d.car*.31+d.wet*wet}
function createQualLap(d,isPlayer){let ability=qualAbility(d,isPlayer),base=baseQualLap()+(S.weather==='Wet'?8:S.weather==='Mixed'?3:0),lap=base+(82-ability)*.095+rnd(-.42,.42);let s1=lap*(.31+rnd(-.004,.004)),s2=lap*(.36+rnd(-.004,.004)),s3=lap-s1-s2;return{player:isPlayer,id:isPlayer?'player':d.id,name:isPlayer?S.name:d.name,lap,s1,s2,s3,ability}}
function qualSession(){if(S.phase!=='qualifying')return;let all=[createQualLap(null,true),...S.field.map(d=>createQualLap(d,false))].sort((a,b)=>a.lap-b.lap);let best=all[0].lap,prev=null;all.forEach((d,i)=>{d.pos=i+1;d.gap=d.lap-best;d.interval=prev?d.lap-prev.lap:0;prev=d});let bestS1=Math.min(...all.map(x=>x.s1)),bestS2=Math.min(...all.map(x=>x.s2)),bestS3=Math.min(...all.map(x=>x.s3));all.forEach(d=>{d.bestS1=Math.abs(d.s1-bestS1)<.0005;d.bestS2=Math.abs(d.s2-bestS2)<.0005;d.bestS3=Math.abs(d.s3-bestS3)<.0005});S.lastQual={session:S.series===4?'Q'+(S.qualStage+1):'Qualifying',all};S.qualHistory.push({track:cur().tracks[S.round],session:S.lastQual.session,all:all.map(x=>({...x}))});if(S.series===4){S.qualStage++;let p=all.findIndex(x=>x.player)+1;if((S.qualStage===1&&p>15)||(S.qualStage===2&&p>10)||S.qualStage===3){S.grid=p;finishQual(all)}else{notice(`Advanced to Q${S.qualStage+1}.`);renderQualTable(all.slice(0,S.qualStage===1?15:10));renderQual();save();return}}else{S.grid=all.findIndex(x=>x.player)+1;finishQual(all)}}
function finishQual(all){if(S.grid===1){S.career.poles++;hist('⏱️ Pole position at '+cur().tracks[S.round])}S.phase=S.sprint?'sprint':'race';renderQualTable(all);notice(`Qualified P${S.grid}. Choose your race strategy.`);render();save()}
function sectorClass(v,best){return best?'sector best':'sector'}
function renderQualTable(all){if(!all)return;$('qualResults').innerHTML='<table><tr><th>Pos</th><th>Driver</th><th>Best lap</th><th>Gap</th><th>Interval</th><th>S1</th><th>S2</th><th>S3</th></tr>'+all.map((d,i)=>`<tr class="${d.player?'you':''}"><td>P${i+1}</td><td>${d.name}</td><td>${lapTimeFmt(d.lap)}</td><td>${i===0?'POLE':'+'+d.gap.toFixed(3)+'s'}</td><td>${i===0?'—':'+'+d.interval.toFixed(3)+'s'}</td><td class="${sectorClass(d.s1,d.bestS1)}">${d.s1.toFixed(3)}</td><td class="${sectorClass(d.s2,d.bestS2)}">${d.s2.toFixed(3)}</td><td class="${sectorClass(d.s3,d.bestS3)}">${d.s3.toFixed(3)}</td></tr>`).join('')+'</table>'}
function renderQual(){$('qualTitle').textContent=S.series===4?`F1 Qualifying ${S.phase==='qualifying'?'- Q'+(S.qualStage+1):''}`:'Qualifying';$('qualBadge').textContent=S.grid?'P'+S.grid:(S.phase==='qualifying'?'Ready':'Not run');$('gridBadge').textContent=S.grid?'Grid P'+S.grid:'No grid';$('qualBtn').disabled=!['practice','qualifying'].includes(S.phase);$('qualBtn').textContent=S.phase==='practice'?'Skip remaining practice → Qualifying':'Run qualifying session';$('raceBtn').disabled=!(S.phase==='race'||S.phase==='sprint')||!!S.race;$('raceBtn').textContent=S.phase==='sprint'?'Start sprint':'Start race';if(S.lastQual&&S.phase!=='qualifying')renderQualTable(S.lastQual.all);renderStrategyAdvice()}
function qualifyingAction(){if(S.phase==='practice'){S.practice=0;S.phase='qualifying';notice('Practice skipped. Qualifying is ready.');render();save();return}qualSession()}
function renderStrategyAdvice(){let tyre=$('startTyre').value||'Medium',life=TYRES[tyre]?.life||28,laps=cur().laps,window=Math.max(3,Math.min(laps-3,Math.round(life*.72)));$('strategyAdvice').innerHTML=S.grid?`Predicted ${tyre} life: <strong>${life} laps</strong> • Recommended first stop: <strong>Lap ${Math.max(3,window-2)}–${Math.min(laps-2,window+2)}</strong> • Pit loss estimate: <strong>${pitLossEstimate().toFixed(1)}s</strong>`:'Qualify to receive tyre-life and pit-window predictions.'}
function pitLossEstimate(){return Math.max(14,22+S.series*1.2-S.dev.pit*.65)}
function startRace(){if(!(S.phase==='race'||S.phase==='sprint')||!S.grid)return;let laps=S.phase==='sprint'?Math.max(10,Math.round(cur().laps*.32)):cur().laps;let tyre=$('startTyre').value;if(S.weather==='Wet'&&tyre!=='Intermediate')tyre='Intermediate';let racers=[makePlayerRacer(tyre),...S.field.map((d,i)=>makeAIRacer(d,i))];racers.sort((a,b)=>a.pos-b.pos);S.race={lap:0,laps,racers,sc:0,red:false,weather:S.weather,playerFuel:100,playerERS:100,feed:[],pending:null,sprint:S.phase==='sprint',baseLap:[55,96,93,92,90][S.series]||90,pitHistory:[],fastest:null,sectorBest:{s1:null,s2:null,s3:null},strategyStart:{grid:S.grid,tyre,risk:$('risk').value,ers:$('ers').value,fuel:$('fuel').value,paceMode:$('paceMode').value}};feed('🏁 '+(S.phase==='sprint'?'Sprint':'Race')+' started from P'+S.grid+'.');$('raceBtn').disabled=true;renderRace();save()}
function makePlayerRacer(tyre){return{player:true,id:'player',name:S.name,pos:S.grid,skill:S.stats.pace*.25+S.stats.racecraft*.3+S.stats.consistency*.16+car()*.29,wet:S.stats.wet,cons:S.stats.consistency,car:car(),tyre,wear:0,gap:0,damage:0,pits:0,dnf:false,totalTime:(S.grid-1)*.18,lastLap:null,sectors:null,team:team()[0]}}
function makeAIRacer(d,i){let pos=i+1+(i>=S.grid?1:0);return{id:d.id,name:d.name,pos,skill:d.skill*.48+d.cons*.15+d.car*.37,wet:d.wet,cons:d.cons,car:d.car,tyre:S.weather==='Wet'?'Intermediate':['Soft','Medium','Hard'][ri(0,2)],wear:0,gap:0,damage:0,pits:0,dnf:false,totalTime:(pos-1)*.18,lastLap:null,sectors:null,team:cur().teams[d.teamTier||0][0]}}
function advance(n=1){if(!S.race)return;for(let i=0;i<n&&S.race&&S.race.lap<S.race.laps;i++){if(S.race.pending)break;simLap()}renderRace();render();save()}
function simLap(){let r=S.race;r.lap++;if(r.sc>0)r.sc--;let changeChance=S.forecast==='Rain possible'||S.forecast==='Changeable'?0.025:.006;if(Math.random()<changeChance){r.weather=r.weather==='Dry'?'Wet':'Dry';feed('🌦️ Weather change: '+r.weather+' conditions.');radio('Weather change','Pit for suitable tyres?',[['Pit now','pit'],['Stay out','stay']])}
 let risk={Low:-.5,Medium:0,High:.7}[$('risk').value],ers={Save:-.35,Balanced:0,Attack:.7}[$('ers').value],fuel={Conserve:-.3,Balanced:0,Push:.55}[$('fuel').value],paceMode={Conserve:{pace:-.75,wear:.62,mistake:.55,fuel:.96,ers:2},Balanced:{pace:0,wear:1,mistake:1,fuel:1,ers:0},Push:{pace:.75,wear:1.38,mistake:1.35,fuel:1.05,ers:-2},Attack:{pace:1.25,wear:1.72,mistake:1.8,fuel:1.1,ers:-4}}[$('paceMode').value]||{pace:0,wear:1,mistake:1,fuel:1,ers:0};r.playerERS=clamp(r.playerERS+($('ers').value==='Save'?3:$('ers').value==='Attack'?-5:0)+paceMode.ers,0,100);r.playerFuel=clamp(r.playerFuel-(100/r.laps)*($('fuel').value==='Push'?1.08:$('fuel').value==='Conserve'?.92:1)*paceMode.fuel,0,100);
 r.racers.forEach(d=>{if(d.dnf)return;if(!Number.isFinite(d.totalTime))d.totalTime=(d.pos-1)*.18;let t=TYRES[d.tyre]||TYRES.Medium;let stintWear=t.wear*(r.sc?.35:1)*(d.player?paceMode.wear:rnd(.9,1.18));d.wear+=stintWear;let tyrePenalty=Math.max(0,d.wear-55)*.055;let wetFit=r.weather==='Wet'?(d.tyre==='Intermediate'?2.2:-3.8)+(d.wet-50)*.045:(d.tyre==='Intermediate'?-3.2:0);let p=d.skill+t.pace-tyrePenalty+wetFit+rnd(-2.1,2.1)-d.damage*.12;if(d.player)p+=risk+ers+fuel+paceMode.pace;let lapNoise=r.sc?rnd(-.08,.08):rnd(-.38,.38);let lapTime=r.baseLap+(82-p)*.082+lapNoise;if(r.weather==='Wet')lapTime+=8.5;if(r.sc)lapTime=r.baseLap+17+rnd(-.15,.15);let errBase=.003+(65-d.cons)*.00045+(d.player&&$('risk').value==='High'?.008:0)+(r.weather==='Wet'?.005:0);let err=clamp(errBase*(d.player?paceMode.mistake:1),.001,.055);if(Math.random()<err){if(Math.random()<.28){d.dnf=true;d.lastLap=null;feed('💥 '+d.name+' crashed and retired.');if(Math.random()<.45){r.sc=ri(2,4);feed('🚨 Safety Car deployed.')}}else{let lost=rnd(2.5,9);d.damage=clamp(d.damage+rnd(4,18),0,60);lapTime+=lost;feed('⚠️ '+d.name+' made a mistake and lost '+lost.toFixed(1)+'s.')}}let mech=(100-(d.player?rel():Math.min(96,d.car+8)))*.00035;if(Math.random()<mech){d.dnf=true;d.lastLap=null;feed('🔧 '+d.name+' retired with a mechanical failure.')}if(!d.dnf){d.lastLap=Math.max(1,lapTime);let s1=d.lastLap*(.31+rnd(-.003,.003)),s2=d.lastLap*(.36+rnd(-.003,.003)),s3=d.lastLap-s1-s2;d.sectors={s1,s2,s3};updateSectorBests(d);d.totalTime+=d.lastLap;updateFastest(d)}});
 aiPitLogic();let alive=r.racers.filter(x=>!x.dnf).sort((a,b)=>a.totalTime-b.totalTime);if(r.sc&&alive.length){let lead=alive[0].totalTime;alive.forEach((d,i)=>d.totalTime=lead+i*rnd(.18,.42))}let dead=r.racers.filter(x=>x.dnf).sort((a,b)=>(a.pos||99)-(b.pos||99));r.racers=[...alive,...dead];normalizeTiming(r);let p=r.racers.find(x=>x.player);if(p&&p.wear>75&&!r.pending)radio('Tyres fading',`${p.tyre} wear is ${Math.round(p.wear)}%. Pit now?`,[['Pit','pit'],['Stay out','stay']]);if(r.lap===Math.round(r.laps*.48)&&!r.pending)radio('Undercut window',`Cars around you are entering the pit window. Current predicted pit loss ${pitLossEstimate().toFixed(1)}s.`,[['Box this lap','pit'],['Extend stint','stay']]);if(r.lap===Math.round(r.laps*.7)&&Math.random()<.08){r.red=true;feed('🟥 Red flag. Race suspended and field reset.');let alive2=r.racers.filter(d=>!d.dnf);if(alive2.length){let lead=alive2[0].totalTime;alive2.forEach((d,i)=>d.totalTime=lead+i*.25)}}if(r.lap>=r.laps)finishRace()}
function updateSectorBests(d){let r=S.race;if(!d.sectors)return;['s1','s2','s3'].forEach(k=>{if(r.sectorBest[k]===null||d.sectors[k]<r.sectorBest[k])r.sectorBest[k]=d.sectors[k]})}
function updateFastest(d){let r=S.race;if(!d.lastLap)return;if(!r.fastest||d.lastLap<r.fastest.time)r.fastest={id:d.id,name:d.name,time:d.lastLap,lap:r.lap}}
function aiPitLogic(){let r=S.race;r.racers.forEach(d=>{if(d.player||d.dnf)return;let life=TYRES[d.tyre]?.life||28;let should=d.wear>76||r.lap>life*.72&&r.lap<r.laps-5&&Math.random()<.08;if(should)performPit(d,false)})}
function radio(title,text,choices){if(S.race.pending)return;S.race.pending={title,text,choices}}
function performPit(d,isPlayer=true){let r=S.race;d.pits++;let old=d.tyre;d.wear=0;d.tyre=r.weather==='Wet'?'Intermediate':(old==='Soft'?'Medium':old==='Medium'?'Hard':'Medium');let pitLoss=Math.max(14,22+S.series*1.2-(isPlayer?S.dev.pit:ri(0,6))*.65+rnd(-.8,.8));d.totalTime+=pitLoss;r.pitHistory.push({lap:r.lap,driver:d.name,from:old,to:d.tyre,loss:pitLoss});if(isPlayer)feed('🔧 Pit stop: '+old+' → '+d.tyre+' • '+pitLoss.toFixed(1)+'s loss.');return pitLoss}
function chooseRadio(action){let r=S.race,p=r.racers.find(x=>x.player);if(action==='pit')performPit(p,true);else feed('📻 You stayed out and extended the stint.');r.pending=null;normalizeTiming(r);renderRace();save()}
function finishRace(){let r=S.race,p=r.racers.find(x=>x.player),finish=p.pos,dnf=p.dnf,pts=dnf?0:(r.sprint?[8,7,6,5,4,3,2,1][finish-1]||0:POINTS[finish-1]||0);S.points+=pts;S.career.points+=pts;if(!r.sprint){S.career.starts++;if(dnf)S.career.dnfs++;if(finish===1){S.career.wins++;if(S.series===4)S.career.f1wins++}if(finish<=3&&!dnf)S.career.podiums++;S.career.best=Math.min(S.career.best,finish)}if(r.fastest?.id==='player'){S.career.fastestLaps++;if(!r.sprint&&finish<=10){S.points++;S.career.points++;pts++}}S.standings.player=(S.standings.player||0)+pts;r.racers.forEach((d,i)=>{if(d.player)return;let q=r.sprint?([8,7,6,5,4,3,2,1][i]||0):(POINTS[i]||0);S.standings[d.id]=(S.standings[d.id]||0)+q});let mate=r.racers.find(x=>x.id===S.teammate);if(mate&&!r.sprint){if(!dnf&&finish<mate.pos)S.career.teammateWins++;else S.career.teammateLosses++}S.rep=clamp(S.rep+(dnf?-1:Math.max(-.5,6-finish*.28)),0,100);S.cash+=3+S.series*6+(finish<=10?11-finish:0);if(!r.sprint)awardSuperLicence(finish);S.results.unshift({season:S.season,track:cur().tracks[S.round],kind:r.sprint?'Sprint':'Race',finish:dnf?'DNF':'P'+finish,points:pts});S.lastAnalysis=buildRaceAnalysis(r,p,finish,dnf);hist(`${r.sprint?'Sprint':'Race'} ${dnf?'DNF':'P'+finish} at ${cur().tracks[S.round]}`);feed(`🏁 Finished ${dnf?'DNF':'P'+finish} • ${pts} points.`);if(r.sprint){S.race=null;S.phase='race';notice('Sprint complete. Main race ready.');render();save();return}S.race=null;S.round++;S.grid=null;S.qualStage=0;S.practice=3;S.phase='practice';if(S.round>=cur().rounds)endSeason();else{weather();S.sprint=S.series===4&&Math.random()<.25;maybeOffer();maybeAcademyOffer();notice('Next race weekend ready.')}render();save()}
function awardSuperLicence(finish){if(S.series===0)return;let gain=Math.max(0,(12-finish))*[0,0.18,.28,.45,.8][S.series];S.superLicence=clamp(S.superLicence+gain,0,40)}
function buildRaceAnalysis(r,p,finish,dnf){let start=r.strategyStart?.grid||S.grid||finish,places=start-finish;let pitText=r.pitHistory.filter(x=>x.driver===S.name).map(x=>`L${x.lap}: ${x.from}→${x.to} (${x.loss.toFixed(1)}s)`).join(', ')||'No stops';let tyreScore=p.wear<85?'Tyre management was controlled.':'Tyres were heavily degraded at the finish.';let delta=places>0?`Gained ${places} positions`:(places<0?`Lost ${Math.abs(places)} positions`:'Finished where you started');let strategy=r.strategyStart?`${r.strategyStart.tyre}, ${r.strategyStart.paceMode||'Balanced'} pace, ${r.strategyStart.risk} risk, ${r.strategyStart.ers} ERS`:'—';return{summary:`${dnf?'DNF':`P${finish}`} from P${start}. ${delta}.`,strategy,pits:pitText,tyres:tyreScore,fastest:r.fastest?`${r.fastest.name} ${lapTimeFmt(r.fastest.time)} on lap ${r.fastest.lap}`:'—'}}
function endSeason(){let rows=standingRows(),pos=rows.findIndex(x=>x.player)+1;if(pos===1){S.career.titles++;hist('🏆 '+cur().name+' champion');S.superLicence=clamp(S.superLicence+[0,12,18,30,0][S.series],0,40)}if(S.series<4&&pos<=cur().promotePos&&S.rep>=cur().promoteRep){if(S.series===3&&S.superLicence<40){hist('⚠️ F1 promotion blocked: Super Licence incomplete')}else{S.series++;S.teamTier=0;hist('⬆️ Promoted to '+cur().name)}}else if(pos<=8&&S.teamTier<2){S.teamTier++;hist('📄 Signed by '+team()[0])}driverMarket();S.season++;S.round=0;S.points=0;S.standings={};S.dev.aero=Math.max(0,S.dev.aero-1);S.dev.engine=Math.max(0,S.dev.engine-1);makeField();weather();S.sprint=S.series===4&&Math.random()<.25;S.practice=3;S.phase='practice';S.grid=null;notice('New season begins.');save()}
function driverMarket(){let moves=[];let sample=[...S.field].sort(()=>Math.random()-.5).slice(0,ri(3,6));sample.forEach(d=>{let old=d.teamTier||0,newTier=clamp(old+(Math.random()<.55?1:-1),0,2);if(newTier!==old){moves.push(`${d.name}: ${cur().teams[old][0]} → ${cur().teams[newTier][0]}`);d.teamTier=newTier}});S.market=moves.slice(0,8);if(moves.length)hist('🔄 Driver market reshuffle: '+moves.length+' moves')}
function lapTimeFmt(sec){if(!Number.isFinite(sec))return'—';let m=Math.floor(sec/60),ss=sec-m*60;return m+':'+ss.toFixed(3).padStart(6,'0')}function raceClockFmt(sec){if(!Number.isFinite(sec))return'—';let h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),ss=Math.floor(sec%60);return(h?h+':':'')+String(m).padStart(h?2:1,'0')+':'+String(ss).padStart(2,'0')}
function normalizeTiming(r){if(!r||!Array.isArray(r.racers))return;let alive=r.racers.filter(d=>!d.dnf);alive.forEach((d,i)=>{if(!Number.isFinite(d.totalTime))d.totalTime=(d.pos||i+1-1)*.18});alive.sort((a,b)=>a.totalTime-b.totalTime);let dead=r.racers.filter(d=>d.dnf);r.racers=[...alive,...dead];let leader=alive[0],prev=null;r.racers.forEach((d,i)=>{d.pos=i+1;if(d.dnf){d.gap=null;d.interval=null;return}d.gap=leader?Math.max(0,d.totalTime-leader.totalTime):0;d.interval=prev?Math.max(0,d.totalTime-prev.totalTime):0;prev=d});r.leaderTime=leader?leader.totalTime:0}
function gapFmt(d,r){if(d.dnf)return'OUT';if(d.pos===1)return'LEADER';let gap=Number.isFinite(d.gap)?d.gap:0,base=r.baseLap||90;if(gap>=base*.92){let laps=Math.max(1,Math.floor(gap/base));return'+'+laps+' Lap'+(laps>1?'s':'')}return'+'+gap.toFixed(3)+'s'}
function intervalFmt(d,r){if(d.dnf||d.pos===1)return'—';let gap=Number.isFinite(d.interval)?d.interval:0,base=r.baseLap||90;if(gap>=base*.92)return'+1 Lap';return'+'+gap.toFixed(3)+'s'}
function pitTable(){let r=S.race;normalizeTiming(r);return'<table><tr><th>Pos</th><th>Driver</th><th>Gap</th><th>Interval</th><th>Recent lap</th><th>Tyre</th><th>Wear</th><th>Status</th></tr>'+r.racers.slice(0,20).map(d=>`<tr class="${d.player?'you timing-you':''}"><td>P${d.pos}</td><td>${d.name}</td><td><strong>${gapFmt(d,r)}</strong></td><td>${intervalFmt(d,r)}</td><td class="${r.fastest?.id===d.id?'fastest':''}">${lapTimeFmt(d.lastLap)}</td><td>${d.tyre}</td><td>${Math.round(d.wear)}%</td><td>${d.dnf?'OUT':d.damage>15?'Damage':'Running'}</td></tr>`).join('')+'</table>'}
function renderRace(){let r=S.race;if(!r){$('raceStatus').textContent='Race not started';$('lapBadge').textContent='Lap —';$('timing').innerHTML='Start the race to see live timing.';$('lapBtn').disabled=$('fiveBtn').disabled=$('autoBtn').disabled=true;$('radioBox').classList.add('hidden');$('raceIntel').innerHTML='No race data yet.';return}normalizeTiming(r);$('raceStatus').textContent=(r.sc?'Safety Car • ':'')+(r.weather==='Wet'?'Wet':'Dry')+' race • Leader '+raceClockFmt(r.leaderTime);$('lapBadge').textContent=`Lap ${r.lap}/${r.laps}`;$('timing').innerHTML=pitTable();$('lapBtn').disabled=$('fiveBtn').disabled=$('autoBtn').disabled=!!r.pending;if(r.pending){$('radioBox').classList.remove('hidden');$('radioBox').innerHTML=`<strong>📻 ${r.pending.title}</strong><div>${r.pending.text}</div><div class="choices">${r.pending.choices.map(c=>`<button data-radio="${c[1]}">${c[0]}</button>`).join('')}</div>`;document.querySelectorAll('[data-radio]').forEach(b=>b.onclick=()=>chooseRadio(b.dataset.radio))}else $('radioBox').classList.add('hidden');let p=r.racers.find(x=>x.player),life=TYRES[p.tyre]?.life||28,mode=$('paceMode').value,modeMult={Conserve:.62,Balanced:1,Push:1.38,Attack:1.72}[mode]||1,est=Math.max(1,Math.round((100-p.wear)/((100/life)*modeMult)));$('raceIntel').innerHTML=`<strong>Driving mode:</strong> ${mode}<br><strong>Fastest:</strong> ${r.fastest?`${r.fastest.name} ${lapTimeFmt(r.fastest.time)} (L${r.fastest.lap})`:'—'}<br><strong>Your tyre estimate:</strong> ~${est} laps remaining<br><strong>Suggested pit window:</strong> L${Math.max(r.lap+1,Math.round(life*.65))}–${Math.min(r.laps-1,Math.round(life*.82))}<br><strong>Pit history:</strong> ${r.pitHistory.length?r.pitHistory.slice(-5).map(x=>`${x.driver} L${x.lap} ${x.from}→${x.to}`).join(' • '):'No stops yet'}`}
function feed(t){let box=$('feed'),d=document.createElement('div');d.className='feeditem';d.textContent=t;box.prepend(d);while(box.children.length>30)box.removeChild(box.lastChild)}
function standingRows(){let rows=[{player:true,name:S.name,points:S.standings.player||S.points},...S.field.map(d=>({id:d.id,name:d.name,points:S.standings[d.id]||0}))];return rows.sort((a,b)=>b.points-a.points)}
function renderStandings(){let rows=standingRows();$('standingsTable').innerHTML='<table><tr><th>Pos</th><th>Driver</th><th>Points</th></tr>'+rows.map((d,i)=>`<tr class="${d.player?'you':''}"><td>${i+1}</td><td>${d.name}</td><td>${d.points}</td></tr>`).join('')+'</table>';$('seasonResults').innerHTML='<table><tr><th>Round</th><th>Session</th><th>Result</th><th>Pts</th></tr>'+S.results.filter(x=>x.season===S.season).map(x=>`<tr><td>${x.track}</td><td>${x.kind}</td><td>${x.finish}</td><td>${x.points}</td></tr>`).join('')+'</table>'}
function renderDriver(){let labels={pace:'Pace',racecraft:'Racecraft',consistency:'Consistency',fitness:'Fitness',wet:'Wet skill',feedback:'Feedback'};$('driverStats').innerHTML=`<p><strong>Overall ${overall()}</strong> • Morale ${Math.round(S.morale)}%</p>`+Object.entries(S.stats).map(([k,v])=>`<div class="statrow"><div class="statline"><span>${labels[k]}</span><strong>${Math.round(v)}</strong></div><div class="bar"><span style="width:${v}%"></span></div></div>`).join('');$('superLicenceBox').innerHTML=`<p><strong>${Math.round(S.superLicence)}/40 points</strong>${S.superLicence>=40?' • Eligible for F1':' • 40 required for F1'}</p><div class="slbar"><span style="width:${S.superLicence/40*100}%"></span></div>`;$('ladder').innerHTML=SERIES.map((x,i)=>`<div class="ladderRow ${i===S.series?'current':''}">${i<S.series?'✓':i===S.series?'🏁':'○'} ${x.name}</div>`).join('');$('academyBox').innerHTML=S.academy?`<div class="contract">🎓 ${S.academy}<br><span class="muted">Reputation bonus and better contract access.</span></div>`:'<div class="muted">No academy contract yet.</div>';let rv=S.field.find(x=>x.id===S.rival),tm=S.field.find(x=>x.id===S.teammate);$('rivalBox').innerHTML=rv?`<div class="contract">⚔️ ${rv.name}<br><span class="muted">Your benchmark this season.</span></div>`:'—';$('teammateBox').innerHTML=tm?`<div class="comparison"><span>${S.name}</span><strong>${S.career.teammateWins}-${S.career.teammateLosses}</strong><span>${tm.name}</span></div><p class="muted">Season benchmark skill: ${Math.round(tm.skill)}</p>`:'—'}
function upgrade(k){let cost=12+S.series*8+S.dev[k]*4;if(S.cash<cost)return notice('Not enough cash for upgrade.');S.cash-=cost;S.dev[k]=clamp(S.dev[k]+2,0,14);notice(k+' upgrade completed.');hist('🔧 Team upgraded '+k);render();save()}
function maybeOffer(){if(Math.random()>.45)return;S.offers=[];if(S.teamTier<2&&S.rep>25+S.series*11){let t=S.teamTier+1;S.offers.push({team:cur().teams[t][0],tier:t,series:S.series,salary:8+S.series*8+t*5,repReq:Math.round(S.rep-5)})}if(S.series<4&&S.rep>cur().promoteRep+8&&Math.random()<.4)S.offers.push({team:SERIES[S.series+1].teams[0][0],tier:0,series:S.series+1,salary:12+(S.series+1)*10,repReq:Math.round(S.rep)})}
function negotiateOffer(i,style){let o=S.offers[i];if(!o)return;let chance=style==='aggressive'?.45:style==='balanced'?.72:.9;let bonus=style==='aggressive'?1.35:style==='balanced'?1.15:1;if(Math.random()<chance){o.salary=Math.round(o.salary*bonus);acceptOffer(i,true)}else{notice('Negotiation failed. The team withdrew the offer.');S.offers.splice(i,1);render();save()}}
function acceptOffer(i,negotiated=false){let o=S.offers[i];if(!o)return;if(o.series>S.series){if(o.series===4&&S.superLicence<40)return notice('You need 40 Super Licence points for F1.');S.series=o.series;S.round=0;S.points=0;S.standings={};makeField();weather()}S.teamTier=o.tier;S.cash+=o.salary||0;S.offers=[];hist('📄 Contract signed: '+o.team+(negotiated?' after negotiation':''));notice('Signed with '+o.team);render();save()}
function maybeAcademyOffer(){if(S.academy||S.series<1||Math.random()>.35)return;S.academyOffers=[['Velocity Academy',3],['Titan Junior Programme',4],['Apex Driver Academy',2]].sort(()=>Math.random()-.5).slice(0,1).map(x=>({name:x[0],bonus:x[1]}))}
function acceptAcademy(i){let a=S.academyOffers[i];if(!a)return;S.academy=a.name;S.rep=clamp(S.rep+a.bonus,0,100);S.academyOffers=[];hist('🎓 Joined '+S.academy);render();save()}
function sponsor(){if(S.sponsor)return;S.sponsor={name:['Velocity Energy','Apex Data','Titan Performance'][ri(0,2)],rounds:6,bonus:4+S.series*3};hist('💼 Sponsor signed: '+S.sponsor.name);render();save()}
function renderTeam(){$('teamName').textContent=team()[0];$('teamInfo').innerHTML=`<p>Car performance <strong>${Math.round(car())}</strong>/100 • Reliability <strong>${Math.round(rel())}</strong>/100</p><p>Aero +${S.dev.aero} • Power +${S.dev.engine} • Reliability +${S.dev.reliability} • Pit crew +${S.dev.pit}</p>`;document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>upgrade(b.dataset.up));$('contracts').innerHTML=S.offers.length?S.offers.map((o,i)=>`<div class="contract"><strong>${o.team}</strong><br><span class="muted">${SERIES[o.series].name} • signing bonus ${fmt(o.salary)}</span><div class="negotiation"><button data-neg="safe:${i}">Accept safely</button><button data-neg="balanced:${i}">Negotiate</button><button data-neg="aggressive:${i}">Push hard</button></div></div>`).join(''):'<div class="muted">No active offers.</div>';document.querySelectorAll('[data-neg]').forEach(b=>b.onclick=()=>{let [style,i]=b.dataset.neg.split(':');if(style==='safe')acceptOffer(+i);else negotiateOffer(+i,style)});$('academyOffers').innerHTML=S.academy?`<div class="contract">Currently signed to ${S.academy}</div>`:(S.academyOffers.length?S.academyOffers.map((a,i)=>`<div class="contract"><strong>${a.name}</strong><br><span class="muted">Reputation bonus +${a.bonus}</span><br><button data-academy="${i}">Join academy</button></div>`).join(''):'<div class="muted">No academy offer currently.</div>');document.querySelectorAll('[data-academy]').forEach(b=>b.onclick=()=>acceptAcademy(+b.dataset.academy));$('sponsorBox').innerHTML=S.sponsor?`<div class="sponsor">💼 ${S.sponsor.name} • ${S.sponsor.rounds} rounds remaining</div>`:'<button id="sponsorBtn">Find sponsor</button>';if($('sponsorBtn'))$('sponsorBtn').onclick=sponsor;$('marketBox').innerHTML=S.market.length?S.market.map(m=>`<div class="marketMove">🔄 ${m}</div>`).join(''):'<div class="muted">Driver market updates appear between seasons.</div>'}
function renderHistory(){let c=S.career;$('careerStats').innerHTML=`<table><tr><th>Starts</th><td>${c.starts}</td></tr><tr><th>Wins</th><td>${c.wins}</td></tr><tr><th>Podiums</th><td>${c.podiums}</td></tr><tr><th>Poles</th><td>${c.poles}</td></tr><tr><th>Fastest laps</th><td>${c.fastestLaps}</td></tr><tr><th>Titles</th><td>${c.titles}</td></tr><tr><th>F1 wins</th><td>${c.f1wins}</td></tr><tr><th>Career points</th><td>${c.points}</td></tr><tr><th>DNFs</th><td>${c.dnfs}</td></tr></table>`;$('historyList').innerHTML=S.history.length?S.history.map(h=>`<div><strong>S${h.season} • ${h.series}</strong><br>${h.t}</div>`).join(''):'<div class="muted">No history yet.</div>';$('raceAnalysis').innerHTML=S.lastAnalysis?`<strong>${S.lastAnalysis.summary}</strong><br><span class="muted">Start strategy:</span> ${S.lastAnalysis.strategy}<br><span class="muted">Pit stops:</span> ${S.lastAnalysis.pits}<br><span class="muted">Tyres:</span> ${S.lastAnalysis.tyres}<br><span class="muted">Fastest lap:</span> ${S.lastAnalysis.fastest}`:'Complete a race to see strategy analysis.'}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});$('qualBtn').onclick=qualifyingAction;$('raceBtn').onclick=startRace;$('lapBtn').onclick=()=>advance(1);$('fiveBtn').onclick=()=>advance(5);$('autoBtn').onclick=()=>{for(let i=0;i<10&&S.race&&!S.race.pending;i++)simLap();renderRace();render();save()};$('saveBtn').onclick=()=>save(true);$('newBtn').onclick=()=>{if(confirm('Start a new career and replace your save?'))$('newDialog').showModal()};['startTyre','risk','ers','fuel','paceMode'].forEach(id=>$(id).onchange=()=>{renderStrategyAdvice();if(S.race){feed('📻 Driving mode set to '+$('paceMode').value+'.');renderRace();save()}});$('newForm').onsubmit=e=>{e.preventDefault();S=fresh($('driverName').value.trim()||'Alex Combes',$('nationality').value,$('archetype').value);makeField();weather();hist('🏁 Career started in Karting');$('newDialog').close();notice('Career started. Begin practice.');render();save()}}
ensure();bind();if(!localStorage.getItem('roadToF1V4')&&!localStorage.getItem('roadToF1V33'))$('newDialog').showModal();render();
